### ISSUE TITLE
séquences ɻ + ̩ +   ̃ et ɻ +   ̃ + ̩  dans l'intitulé du chapitre ɻ̩̃ 

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#100]
L'intitulé du chapitre ɻ ̩̃  est double :  ɻ̩̃ - ɻ̩̃ 
![image](https://github.com/user-attachments/assets/3e9fb23e-5003-486a-9b4f-d72a1b2ea2ac)
Cela est sans doute lié au fait qu'il peut exister en principe des séquences ɻ + ̩ +   ̃ aussi bien que ɻ +   ̃ + ̩  avec le même rendu mais pas avec la même séquence de code Unicode ?

Afin d'éviter qu'il y ait ce titre double, serait-il possible d'intervenir "manuellement" afin qu'il n'y ait qu'un seul affichage (pas d'affichage double) ?

Une autre possibilité consisterait à supprimer de na.lex la double écriture, en n'utilisant que l'une des deux séquences équivalentes. La réapparition dans le PDF d'une double séquence en tête de chapitre serait alors le signe que la séquence 2 a été ré-introduite ici ou là.

Mais après vérification (avec Kate), il semblerait que la combinaison ɻ̩̃ produite comme ɻ +   ̃ + ̩  n'apparaisse nulle part dans le fichier dans son état actuel : la seule combinaison utilisée est ɻ + ̩ +   ̃

**Comment by alexis-michaud** [comment]
(clin d'œil au passage : centième ticket de ce dépôt ! ^^ ça avance...)

**Comment by BenjaminGalliot** [comment]
En effet, je n’ai pas vu la combinaison ɻ̩̃ : il est donc possible de ne placer que l’autre combinaison dans l’ordre lexicographique, ce qui résout le problème (mais attention si plus tard cette combinaison réapparaît ; il y a peut-être d’ailleurs d’autres graphèmes de ce type qu’on n’a pas vus). Sinon, je peux faire en sorte de ne prendre que la première combinaison comme lettrine dans le fichier LaTeX/PDF le cas échéant.

**Comment by alexis-michaud** [comment]
> En effet, je n’ai pas vu la combinaison ɻ̩̃ : il est donc possible de ne placer que l’autre combinaison dans l’ordre lexicographique, ce qui résout le problème (mais attention si plus tard cette combinaison réapparaît ; il y a peut-être d’ailleurs d’autres graphèmes de ce type qu’on n’a pas vus). 

Faisons comme ça, c'est bien : ne placer que l'autre combinaison dans l'ordre lexicographique.
Le toilettage périodique est de toute façon souhaitable, pour vérifier que na.lex est conforme à ce qui est souhaité.

> Sinon, je peux faire en sorte de ne prendre que la première combinaison comme lettrine dans le fichier LaTeX/PDF le cas échéant (mais niveau propreté, cela laisse à désirer, car on laisserait un graphème complexe non utilisé dans l’ordre lexicographique ; et s’il y a d’autres combinaisons de ce type, il faudrait aussi les insérer, par cohérence).

Oui, mieux vaut éviter cette solution façon "rabibochage", ça n'est pas l'esprit Lexika, qui est carré ! :1234: 
 
> En attendant, j’ai supprimé cette combinaison de l’ordre lexicographique, et aucun imprévu n’est survenu !

:100: :+1: 
Je ferme le ticket !
