### ISSUE TITLE
Composer des extraits de XML Lexika (dont le caractère ⓔ) dans l'intro du dictionnaire

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#101]
L'introduction explique la façon dont est constitué l'identifiant d'une entrée : l'identifiant "est composé du caractère spécial {ⓔ} suivi de la représentation phonologique du mot".
La police Garamond ne contenant pas de glyphe pour ce caractère, il faudrait le composer dans une police qui le contienne. 
![image](https://github.com/user-attachments/assets/e6a36a5a-62eb-40e4-9a4b-bc63b0e74610)

La même question se pose pour l'extrait du code XML Lexika qu'il était prévu de présenter dans l'introduction : il faudrait une police "trapue" qui peut afficher tout ce qu'il faut.
![image](https://github.com/user-attachments/assets/17f3d440-7030-4f93-b002-df191022f7be)
```

\begin{lstlisting}[caption=Extrait du code XML Lexika illustrant la structure des entrées, label=code:LexikaXMLListing, basicstyle=\footnotesize\ttfamily\setmonofont{NotoSans}]
      <EntréeLexicale identifiant="ⓔhĩ˧-ʈʂɤ#˥">
        <Lemme>
          <Forme>hĩ˧-ʈʂɤ#˥</Forme>
          <Ton>#H</Ton>
...
```

Idem pour le caractère spécial ◈ qui introduit les notes (/commentaires).

**Comment by BenjaminGalliot** [comment]
J’ai rapidement testé quelques polices, et celles-ci semblent avoir ces glyphes :
- Noto Sans Symbols ;
- Linux Biolinium ;
- Linux Libertine ;
- Symbola (mais elle semble un peu problématique à cause de sa licence).

Il faudra les tester individuellement pour le rendu car les glyphes de ce type peuvent avoir des apparences (incluant la taille et la hauteur) très variables. Il faudra ne pas hésiter non plus à utiliser des polices de remplacement en cascade.

D’ailleurs, je me rends compte en voyant cet exemple qu’on pourrait avoir un XML chinois rapidement si on arrive à avoir des traductions (au moins pour les éléments XML montrés dans l’introduction).

**Comment by alexis-michaud** [comment]
> J’ai rapidement testé quelques polices, et celles-ci semblent avoir ces glyphes :
> 
>     * Noto Sans Symbols ;
> 
>     * Linux Biolinium ;
> 
>     * Linux Libertine ;
> 
>     * Symbola (mais elle semble un peu problématique à cause de sa licence).

C'est toi qui connais, tellement mieux que moi que je m'en voudrais de faire semblant d'imaginer que je peux apporter une contribution utile à cette tâche. Noto Sans Symbols (la version 2, j'imagine ?) contient bcp de caractères, ils ont bossé. Personnellement, j'aime bien Linux Libertine (comme elle a été choisie par Language Science Press, je sais à qui poser des questions si besoin) et le fait d'utiliser un outil libre plutôt qu'un outil "Google libre" paraît attirant quand pour le reste c'est à peu près bonnet blanc et blanc bonnet.

> Il faudra les tester individuellement pour le rendu car les glyphes de ce type peuvent avoir des apparences (incluant la taille et la hauteur) très variables. Il faudra ne pas hésiter non plus à utiliser des polices de remplacement en cascade.

Je n'y connais presque rien **(bis repetita)**. Dans quel sens tu t'orientes : avoir un style \xml{} pour l'affichage d'extraits de XML ? Si oui, le choix d'une apparence différente est plutôt souhaitable, au fond, non ? 
 
> D’ailleurs, je me rends compte en voyant cet exemple qu’on pourrait avoir un XML chinois rapidement si on arrive à avoir des traductions (au moins pour les éléments XML montrés dans l’introduction).

Oui, la mise au point d'un lexique trilingue (voire, à terme, étendu aux langues cibles elle-même) paraîtrait un bon objectif pour disons les 6 mois qui viennent. Il faudrait un peu de concertation afin que les termes choisis conviennent au premier cercle de Lexika (peut-être les équipes des 3 ou 4 ou 5 ou 6 premiers dictionnaires disons ?)

Un Wiki "Lexika" pourrait être bien pour ça ? ou Zulip ?

**Comment by BenjaminGalliot** [comment]
J’avais oublié de fermer ce ticket, comme l’affichage du code est fonctionnel.

![Copie d'écran_20241015_160603](https://github.com/user-attachments/assets/a37d27e9-9185-45cb-ae65-5fff5b192bfd)
