### ISSUE TITLE
dictionnaire, versions française et anglaise : typographie

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#102]
Quelques points : 

- Pas d'espace avant les deux points pour la version anglaise (ici après la liste des locuteurs pour variantes)
![Capture d’écran du 2024-10-29 21-24-53](https://github.com/user-attachments/assets/c596211f-edd3-431c-9945-04bbb99f9fae)
- métadonnées : où mentionner le numéro de version ? Celle-ci étant la 2.0. Une mention dans la deuxième de couverture me paraîtrait bien, et si ça ne te choque pas que ça apparaisse en couverture intérieure, je trouve que ça pourrait être pas mal, mais c'est toi @BenjaminGalliot qui définis les gabarits. 
- mention "Élicitation phonologique" pour les exemples PHONO, et pas juste "phonologie"
- partie du discours (classe morphosyntaxique) en petites capitales

**Comment by BenjaminGalliot** [comment]
J’ai corrigé les deux-points pour les versions chinoise et anglaise (le bloc complet n’avait pas d’indicateur de langue…).

Actuellement, le numéro de version se trouve uniquement dans le lien HAL, je vais donc l’ajouter de manière plus claire ailleurs sur cette page, qui est actuellement en cours de travaux !

J’ai remplacé l’indication de phonologie pour l’anglais et le français.

![Copie d'écran_20241030_150404](https://github.com/user-attachments/assets/0eb0436d-9432-4f86-9dad-801e75ddaa81)
![Copie d'écran_20241030_150254](https://github.com/user-attachments/assets/bad811cb-f95c-4d6c-90f7-8acf64cbd46b)

Je découvre au passage qu’on peut couper le mot « elicitation » [à cet endroit en anglais](https://www.hyphenation24.com/word/elicitation/)…

Les parties du discours sont déjà en petites capitales… Aurais-tu à nouveau cet étrange problème avec les polices locales ?

**Comment by BenjaminGalliot** [comment]
J’en ai profité pour corriger la virgule des variantes, qui prenait la couleur des locuteurs…

![Copie d'écran_20241030_155605](https://github.com/user-attachments/assets/17d12551-a4a7-4327-8840-3fab08e292ca)

**Comment by alexis-michaud** [comment]
> Les parties du discours sont déjà en petites capitales… Aurais-tu à nouveau cet étrange problème avec les polices locales ?

Non non, ça marche pour la version chinoise, ça doit donc être un souci de définition de la langue de ce bloc pour les versions fra & eng, dans la version de Lexika que j'utilise.

**Comment by alexis-michaud** [comment]
Travail en cours
