### ISSUE TITLE
dictionnaire en version chinoise : traduction types de commentaires : "usage" en chinois

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#105]
Dans la version chinoise, l'attribut des commentaires est globalement bien traduit : une note/commentaire de type `"synt"` aura en chinois la marque 语法, etc.
Il semble que l'attribut de type `"usage"` , lui, ne soit pas traduit :
![image](https://github.com/user-attachments/assets/9756ab62-28a2-4a07-a6c1-f33b07eef8ff)
J'ai un peu oublié où se trouve la liste des traductions... Sauf erreur de ma part, en anglais ça devrait donner : 语用 (qui désigne la pragmatique, l'usage). 
Serait-il possible de vérifier que tout est bon de ce côté-là ? Merci !

**Comment by BenjaminGalliot** [comment]
![Copie d'écran_20241112_201247](https://github.com/user-attachments/assets/0af18a8f-d433-410d-a5eb-70b0b508c0e5)

C’est fait !
