### ISSUE TITLE
traitement du bloc "Morphologie" du dictionnaire

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#106]
Dans le dictionnaire en version française, ni les traductions ni les commentaires en anglais n'apparaissent, normalement. 
Dans la version actuelle, les commentaires morphologiques 
`\mc <langue="eng">` 
sont affichés : 
![image](https://github.com/user-attachments/assets/edf82324-1b7b-407a-a538-ad80a4c47977)

**Comment by alexis-michaud** [comment]
Dans le dico en langue anglaise, la réciproque est vraie.
![image](https://github.com/user-attachments/assets/ffebe6aa-a28e-46c1-9be2-bf5c86e93edd)
Il faudrait donc modifier un paramètre de façon à ce que seuls les `\mc` dans la langue de l'interface soient affichés pour le français et l'anglais. 

(La version chinoise se distingue ici, puisqu'en gros tout y est affiché : c'est un dico vraiment quadrilingue. Pour les `\mc` comme pour les notes & commentaires présentant d'autres attributs, ça s'affiche dans les 3 langues, pas la peine de filtrer / d'exclure.)

**Comment by BenjaminGalliot** [comment]
Ah, j’ai compris, c’est parce que c’est un commentaire et non une note. Ça date, mais je crois qu’on avait eu une discussion sur ça, notamment pour la morphologie, un cas particulier, etc. Je ne sais plus où ça se trouve, mais c’est la source de cette différence. Je m’en occupe bientôt, mais j’aimerais retrouver les raisons de cette différence de traitement…

**Comment by alexis-michaud** [comment]
Tout à fait. La morphologie est traitée comme un bloc à part. 

Les commentaires morphologiques \mc ne peuvent être posés que s'il existe un découpage morphologique : au moins un champ \mr qui indique de quoi le mot est composé (par exemple pour "pied de biche" il y aurait 
\mr pied
\mr de
\mr biche
et tous les commentaires \mc qu'on peut souhaiter. Mais pas de commentaire morphologique sans \mr.

Le traitement est donc séparé. 
C'est une info qui t'est utile ?

**Comment by alexis-michaud** [comment]
À la réflexion, l'emploi d'un beau symbole de derrière les fagots (Symbola) ne serait pas inutile pour séparer ce fameux bloc "Morphologie" de ce qui précède. À l'heure actuelle, seule une espace un peu plus longue que la normale (me semble-t-il) le sépare du texte qui précède. De sorte qu'il succède de façon un petit peu abrupte au texte qui précède. 
Exemple en première page du dico (version française) : 
![image](https://github.com/user-attachments/assets/40fd0176-97a4-4190-b3fc-c5a1b58d687e)

Quand on avait regardé ensemble, ce symbole nous avait tapé dans l'œil : ⁜ 
Elle convient pour cet usage, non ? La croix évoquant la structure du mot complet (quelque chose de charpenté), et les points les morphèmes, éléments séparés (et plus nombreux) qui entrent dans la composition morphologique du mot ?

Par ailleurs, je reviendrais volontiers à la formule "Composition morphologique", plutôt que "Morphologie", qui à la réflexion me paraît trop vague pour éclairer les lectrices & lecteurs. Les noms de domaines de la linguistique (sémantique, syntaxe, dialectologie etc.) sont utilisés comme étiquettes pour des notes/commentaires (des champs "texte"). Là, en revanche, pour \mr, il s'agit de quelque chose de précisément défini : le champ \mr contient un des morphèmes dont est constituée l'entrée lexicale en question. C'est nettement plus long que "Morphologie", mais on y gagne nettement en clarté.

**Comment by alexis-michaud** [comment]
Parmi les autres symboles cabalistiques mignons de Symbola : 
▣
☉
❊

**Comment by BenjaminGalliot** [comment]
> Tout à fait. La morphologie est traitée comme un bloc à part.
> 
> Les commentaires morphologiques \mc ne peuvent être posés que s'il existe un découpage morphologique : au moins un champ \mr qui indique de quoi le mot est composé (par exemple pour "pied de biche" il y aurait \mr pied \mr de \mr biche et tous les commentaires \mc qu'on peut souhaiter. Mais pas de commentaire morphologique sans \mr.
> 
> Le traitement est donc séparé. C'est une info qui t'est utile ?

Justement, je crois que c’était l’inverse, qu’il y a parfois des `\mc` sans forcément de `\mr`, et que c’était un moyen d’éviter des ambiguïtés avec des apparentements fâcheux d’entités… En tout cas, c’est ce que j’ai pu vérifier à l’instant, et tout passer en notes crée justement ces désordres…

Quant aux symboles, oui, et pas forcément que pour le bloc de morphologie : plein de blocs (cognats, comparanda, classificateurs, etc.) commencent à la suite du bloc précédent simplement avec un espace plus large, mais la question des symboles pourrait être pertinente ici aussi (certains blocs sans symboles, d’autres avec ; chaque bloc avec son symbole ; chaque bloc avec le même symbole séparateur…)

**Comment by alexis-michaud** [comment]
Du coup c'est parti pour 
**Composition morphologique
Morphological makeup
形态构成**
