### ISSUE TITLE
dictionnaire fra et eng : espace à ajouter avant les *comparanda*

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#107]
Comme discuté sur Zulip : 
La visibilisation des comparanda en langue pumi (qui auparavant étaient tous en `print="n"` , par un choix contestable de ma part) révèle que l'espace est discret (absent ?) après la parenthèse qui indique la langue des comparanda : 
(pumi)bu51
![image](https://github.com/user-attachments/assets/f15752d4-be39-4762-951d-95021049f81d)

Même chose pour le dico anglais : 
![image](https://github.com/user-attachments/assets/0c122550-3d87-44cd-b779-70c0cd9d009e)

(La version chinoise, elle, est impeccable : les parenthèses chinoises sont parfaites pour ça !
![image](https://github.com/user-attachments/assets/dd9e0dad-998f-4864-b590-6790a5f3e5b9)
)

**Comment by BenjaminGalliot** [comment]
![Copie d'écran_20241112_204250](https://github.com/user-attachments/assets/fa96393c-27d2-47ab-9cdc-da6bce1d4ba6)

![Copie d'écran_20241112_204312](https://github.com/user-attachments/assets/dfe19296-67eb-479e-9cb5-7537393421e6)


C’est réglé, comparanda et cognats ont été ajustés (et j’ai ajouté le même espace avant ces petits blocs).

**Comment by alexis-michaud** [comment]
Super !!
Je rouvre juste parce qu'en anglais le mot est _cognate_ (pluriel _cognates_) et pas _cognat_
![Copie d'écran_20241112_204250](https://github.com/user-attachments/assets/fa96393c-27d2-47ab-9cdc-da6bce1d4ba6)
et que je n'ai pas su trouver où faire cette modif' dans général.xsl, désolé...

**Comment by alexis-michaud** [comment]
Bonne question ! 
Personnellement l'emploi systématique du pluriel ne nuirait pas à mon bonheur : comme ci-dessus 
Cognats : (Naxi) by˧

Au singulier, comment dire : ...
Cognat : (Naxi) by˧
Ca paraît suggérer que ce mot n'a un seul cognat, qui est le mot naxi /by˧/. Ce qui n'est pas la bonne info : c'est juste que dans le dico, l'info qu'on a "à l'heure où on met sous presse", en matière de cognats, c'est ce mot-là.
Les cognats et comparanda sont surtout intéressants au sein d'un ensemble : le comparatisme (linguistique historique) se nourrit de la diversité des aperçus fournis par les cognats dans plein de langues. 

Pareil en anglais.
Du coup je serais partisan du pluriel partout.

**Comment by BenjaminGalliot** [comment]
![Copie d'écran_20241112_220053](https://github.com/user-attachments/assets/5c76046e-0b02-4b85-8774-6031b58c4f7c)

On fait ça !

Cette modification est dans le XSL de chaque langue, dans le préambule partiel.
