### ISSUE TITLE
\cf : remplacer "Cf." par "See also" dans le dictionnaire anglais, et aussi "Confer" par "Voir aussi" dans le dictionnaire français

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#108]
À la réflexion (merci du conseil de ne pas publier précipitamment !), "cf." est clairement suranné en anglais. Il est peu à peu remplacé par "see also" et c'est ça qu'il faut adopter. Pour ne pas faire vieillot, "see also" paraît nettement mieux. (Mes excuses d'y réfléchir si tard !)

L'adoption de "see also" donnera un petit air moderne au dictionnaire. Ca règlera aussi au passage le problème de la succession du point de "cf." et des deux points qui suivent, qui n'était pas très heureuse typographiquement (comme évoqué dans Zulip, régler ce problème n'aurait pas été évident car du coup les deux points seraient également supprimés dans la version française, ce qui n'est pas du tout souhaitable).
![image](https://github.com/user-attachments/assets/07eca279-43fd-469b-bb42-8dfbd8dcb2a6)

Je serais tenté de demander également un changement pour la version française, de "Confer" en "Voir aussi". 
- Au plan fonctionnel : "Confer" est un aiguillage "musclé" (un renvoi vers une autre entrée), tandis que "Voir aussi" est une simple ouverture, à chacun·e de suivre ou non le lien. C'est ce second type de lien qui convient mieux.
- Au plan des connotations et du registre de langue: "confer" est un mot latin savant, ça a un côté un peu compassé et austère, qui n'est pas forcément ce qui est souhaité pour ce dictionnaire. (Je suis facilement séduit par le côté "savant" un peu ostentatoire, mais pour un dictionnaire, la préférence accordé au côté classique / universitaire ne doit pas se faire au détriment de l'accueil d'un lectorat qui ne voit pas souvent la forme étendue "confer".)
![image](https://github.com/user-attachments/assets/8fcaaaec-861d-4615-b51b-82ffdffd3b2a)

Un simple "voir" / "see" serait moins adapté, au vu des exemples (suffisamment nombreux je crois) que j'ai examinés. De plus, l'emploi de "voir aussi" / "see also" libère un espace pour un autre type de lien (à l'avenir) : un renvoi par "Voir" (en anglais "See"), pour une entrée qui n'existerait pas vraiment en tant que telle (pas de définition, pas d'exemples etc.) mais constituerait un simple renvoi vers une autre entrée.

**Comment by BenjaminGalliot** [comment]
![Copie d'écran_20241112_201442](https://github.com/user-attachments/assets/7d8bd912-500c-4cee-b2af-d96835a79087)

![Copie d'écran_20241112_201417](https://github.com/user-attachments/assets/6b5baf0e-950b-4a26-8101-80189cd4ee70)

C’est fait !
