### ISSUE TITLE
champ "auteur" du PDF : retrancher "autorat"

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#109]
Hello, 
J'ai bien entendu que les métadonnées du PDF étaient encore en phase de mise en place et de test. C'est un travail en cours, ça ne se veut pas un choix arrêté. Du coup ma remarque ci-dessous est sûrement prématurée (ou tout à fait hors sujet). 

Mais comme on approche de la publication de la version 2.0 (le texte final de la préface de Latami Dashi a été reçu aujourd'hui), je voulais m'assurer que tu (@BenjaminGalliot) prévoyais de revoir le choix effectué pour le champ "auteur" des métadonnées du fichier PDF, où seul ton nom apparaît actuellement (sur les outils de visualisation que j'utilise).
![image](https://github.com/user-attachments/assets/2e42fc77-0400-4aeb-bbe8-c0c3d1c4b81d)
Les outils de prévisualisation présentent, de ce fait, le dictionnaire comme ton ouvrage à toi
![image](https://github.com/user-attachments/assets/4b162ef8-df04-4698-8957-15080d418fb1)

Je pense que tu seras d'accord que c'est plutôt inattendu ? Dans le champ "Auteur", on s'attendrait plutôt à voir les personnes à qui cette qualité est reconnue dans l'ouvrage. Je vois bien les problématiques liées : on connaît les limites du "star system" où seul compte l'auteur, en dialogue avec la Muse, comme si rien de la chaîne éditoriale n'était pertinent. Mais exclure les auteurs & autrices du champ "Auteur", ça serait quand même un "forçage". Il s'agit de veiller à trouver un bon équilibre, en évitant de tomber dans un autre extrême, où l'ensemble se polariserait à nouveau autour d'une seule personne (qui cumule certes des rôles essentiels & stratégiques, personne n'en doute, mais ça n'empêche pas de faire une p'tite place aux autres). 

À toi de voir ce qui conviendrait le mieux à l'esprit (d'équipe) de Lexica, bien sûr. Si tu souhaites que ton nom apparaisse dans le champ "Auteur" du PDF (qui pourrait regrouper, au fond, tous les contributeurs, s'il n'y a pas de champs pour les autres rôles), mon conseil serait de le faire figurer après la liste des "autrices & auteurs" au sens cla-cla du terme ("l'Autorat". _Conseil de l'automobile_).

Pour ma part je verrais bien dans la liste 4 noms : AM, LD, PMM, BG, si ça te va comme ça. 
Avec les noms complets (Alexis Michaud, Latami Dashilamu, Pascale-Marie Milan, Benjamin Galliot), ou pourquoi pas avec les initiales s'il y avait des contraintes de longueur ou simplement si tu souhaitais faire cette innovation, qui rend les noms propres plus discrets et évite de repousser trop loin les personnes qui arrivent au bout d'un champ qui se fait long.

**Comment by BenjaminGalliot** [comment]
En fait, quand je m’étais renseigné sur les champs de métadonnées PDF, notamment [ici](https://tex.stackexchange.com/questions/590864/pdfcreator-vs-pdfproducer-pdf-metadata-in-hyperref-hypersetup), j’avais eu l’impression que ces métadonnées étaient « techniques », donc que l’auteur était le créateur humain du PDF (du fichier, si je puis dire, pas de son contenu, qui, lui, est bien documenté…), et les créateurs et producteurs des logiciels…

Mais en y repensant, et comme visiblement certains logiciels utilisent vraiment ces informations (je savais pour le titre et c’était surtout pour ce champ que je faisais ces métadonnées, mes logiciels ne m’ont en revanche jamais affiché les auteurs, donc tu me l’apprends…), il faudrait en effet que ça suive le reste pour la cohérence. Donc je vais continuer de me renseigner, et au pire, je casserai un peu l’usage et mélangeant dans `pdfcreator` voire `pdfproducer` des humains et des outils…

**Comment by alexis-michaud** [comment]
Je rouvre le ticket juste pour signaler que ça serait bien de supprimer la mention "Autorat" (on en avait parlé), ça me paraîtrait bien pour la circulation de la version en cours auprès des collègues
Merci bcp !!

**Comment by BenjaminGalliot** [comment]
C’est fait.
