### ISSUE TITLE
dictionnaire : affichage du champ \gr : gloses en langue régionale

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#111]
Dans le dictionnaire, les gloses de la base de données lexicale `na.lex` ne sont pas affichées. En effet, leur fonction est de servir pour gloser des textes (les fameuses _gloses interlinéaires_). Dans un dictionnaire, les champs de définition sont nettement mieux pour expliquer les mots de la langue-cible.

Mais du coup **j'ai oublié les gloses en langue régionale**, `\gr`. Il s'agit de la façon dont se dit tel ou tel mot en chinois local. Comme pour le français on appelle ici _poche_ (ouest de la France, sud-ouest) ce qu'ailleurs on nomme _sachet_ ou _sac_.

C'est une information bien utile pour l'utilisation du dictionnaire.

Il y a actuellement une cinquantaine d'entrées qui possèdent un champ `\gr`. Par exemple :

```
\lx qv̩˧dzi˩
\or gheuzzee
\ps n
\sd <langue="fra"> plante
\sd <langue="eng"> plant
\ton L#
(...)
\de |fi{Pinus massoniana D.Don in Lamb.}, Masson's pine, Chinese red pine, horsetail pine. Its seeds are not edible (the fish eat them, but they are poisonous for humans).
\ge Masson_pine
\dn 马尾松。它的松子不能食用：鱼类可以吃，但对人类有毒。
\gn 马尾松
\gr 马松树
\df |fi{Pinus massoniana D.Don in Lamb.}, conifère de la famille des |fi{Pinaceae}. Ses pignes ne sont pas comestibles: les poissons les mangent, mais pour les hommes elles sont vénéneuses.
\gf pin_de_Masson
```

Pour l'affichage : 

- pour la version chinoise : 
 
ce qui serait souhaitable serait d'ajouter ce champ après la définition en chinois. Ainsi ça serait bien en cohérence, je pense. 
Le contenu du champ serait préfixé de la mention suivante : 
当地汉语方言：
elle-même préfixée d'un super-symbole de derrière les fagots. Par exemple celui-ci :
🞚

![image](https://github.com/user-attachments/assets/920775f6-957b-499d-a78b-21f8633d6249)

Au lieu de : 
马尾松 •
il y aurait donc : 
马尾松 🞚 当地汉语方言：马松树 •

- pour la version française :

🞚 En dialecte chinois local : <\gr>
 
- pour la version anglaise : 

🞚 In local Chinese dialect: <\gr>

(intitulés négociables !)

Merci bcp

**Comment by BenjaminGalliot** [comment]
![Copie d'écran_20241120_225200](https://github.com/user-attachments/assets/96586b62-f9b1-4c8b-b3b4-8dea8fff92c0)

Je pense que c’est bon.
