### ISSUE TITLE
dictionnaire : mention illustration de couverture

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#112]
Sur la 2e de couverture (page des métadonnées), il semble qu'il soit d'usage courant d'indiquer une attribution pour l'illustration de couverture. 
Quelque chose comme ceci ? 

Design de la couverture : Benjamin Galliot. 
Images de couverture : photos Alexis Michaud (2007).

en anglais : 

Cover images: photos by Alexis Michaud (2007).

en chinois : 
封面设计：區勄狐
封面图片：米可（2007 年）拍摄

(Ceci dit pour suivre les usages, et marquer qu'on est bien autorisé à utiliser ces photos : ça fait partie des questions pour lesquelles il est important d'être au clair avec les droits d'utilisation, à ce qu'en disait Raphaëlle Chossenot)

**Comment by BenjaminGalliot** [comment]
C’est fait.
