### ISSUE TITLE
dictionnaire : ligne orpheline en début d'entrée

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#114]
Dans le dictionnaire na français.pdf : 
page 1 : 
![image](https://github.com/user-attachments/assets/89265520-cd9e-4aa1-bbb0-d79258957a3c)

page 2 : 
![image](https://github.com/user-attachments/assets/d870b89d-a872-4b76-9ae0-92becc505f04)

page 7 : 
![image](https://github.com/user-attachments/assets/d07c1bf4-b994-434c-af37-a63e174cbdb8)

page 12 : 
![image](https://github.com/user-attachments/assets/f8ea5aa3-cb39-45ea-b44c-7caf08d23a11)

page 13 : 
![image](https://github.com/user-attachments/assets/a2e82531-d64a-43b4-bf54-7856c98e9c78)

Pour la consultation, ça coupe un peu. Quand c'est sur la même page, ça n'est pas une orpheline en fin de page, c'est déjà ça. Mais il arrive que ça soit la dernière ligne de la colonne de droite et donc de la page, et qu'il faille tourner (si on imagine la version papier). Page 22 : 
![image](https://github.com/user-attachments/assets/75b5d813-893a-4ce7-a3c6-4a7308108536)
 
Est-ce que c'est un comportement qu'on laisse comme ça (la perfection n'est pas de ce monde) ? 
Ou y aurait-il un moyen d'éviter une ligne orpheline en début d'entrée (vedette + ce qui suit en première ligne seul en bas d'une colonne) ? Au prix d'une hauteur de colonne pas exactement identique d'une page à l'autre, ou d'une hauteur de colonne pas exactement identique d'une colonne à l'autre de la même page ?

**Comment by alexis-michaud** [comment]
(Je me demande si je n'aurais pas un vague souvenir comme quoi on en aurait déjà parlé et l'idée de jouer avec la taille des colonnes en rejetant des blocs à la colonne suivante aurait été rejetée, pour ne pas nuire à la continuité visuelle de la page. Ne pas hésiter à clore le ticket si c'était le cas.)

**Comment by BenjaminGalliot** [comment]
En fait, ce point de détail a été un véritable cirque pour le dictionnaire tibétain (et là, sur le coup, c’était vraiment un problème à gérer sérieusement car il était thématique, avec plein de titres et sous-titres au milieu des pages…). C’était mieux, mais certains détails ne me plaisaient pas, mais ça ne semblait pas améliorable dans un futur proche. Le détail qui ne me plaisait pas, c’est qu’on pouvait avoir un dépassement contrôlé d’une colonne avec l’ajout de la dernière ligne pour qu’elle évite de se retrouver seule sur sa page, ce qui était globalement bien, mais les 2 colonnes n’étaient plus alignées à cause de ça. J’avais contacté le développeur du module, je sais qu’il avait jeté un œil sur un test Overleaf que je lui avais fourni, mais je n’ai jamais eu de réponse.

Pour le moment, je préfère qu’on place ça dans la liste des améliorations possibles mais non nécessaires. J’essayerai de faire quelques tests tout début décembre, en tirant profit de ce que j’avais fait pour le tibétain, mais je ne promets rien. Ces tests sont longs, ça demande une compilation sur les documents complets à chaque fois car les échantillonnages sont non significatifs, et il y a de nombreux paramètres qu’on peut faire varier et ils s’affectent tous mutuellement…

**Comment by BenjaminGalliot** [comment]
Comme j’avais un peu de temps, j’ai rapidement tester l’évitement des lignes orphelines sur une colonne, avec le mécanisme mentionné plus haut, avec une niveau de 2 sur 4 pour l’importance, à chaque début d’entrée. Sur le test du na français partiel (100 premières entrées), un seul changement réalisé, plutôt positif.

![Copie d'écran_20241121_234643](https://github.com/user-attachments/assets/12b1517e-aed9-4469-9079-bcc94373967b)

**Comment by BenjaminGalliot** [comment]
Prenons cet exemple tiré du français complet (juste pour les lignes orphelines par colonne).
![Copie d'écran_20241122_003027](https://github.com/user-attachments/assets/dc5fb03c-e2cc-45e8-8a58-ef966552e097)
![Copie d'écran_20241122_003036](https://github.com/user-attachments/assets/efab2bc7-ac4b-4dc7-a67a-7a86e07fdfb3)

Tu vois bien que sur la première page, on a évité un première ligne orpheline, mais la conséquence, c’est que sur la page suivante, comme il n’y a aucun paragraphe sur la seconde colonne, et que par défaut, les interlignes ne sont pas flexibles, eh bien les 2 colonnes ne sont plus ajustées.

On pourrait faire des interlignes flexibles, mais c’est très vite inesthétique. On pourrait aussi demander une double flexibilité des sauts de paragraphe (donc pas uniquement ajouter un tout petit peu d’espace en plus, mais aussi en moins), ça ressererait un peu les paragraphes de la colonne de gauche pour qu’elle tente de s’ajuster à celle de droite, inflexible… Selon le nombre de paragraphes, ça peut rester esthétique, mais un tel changement global ferait que ce serait difficile à tester sur un dictionnaire complet car **toutes** les colonnes seraient affectées par ce changement de flexibilité… De plus, là, on parle d’un unique exemple, et selon le nombre de lignes, de sauts de paragraphes, eh bien parfois ça sera esthétique, parfois non, mais le moindre changement retournera toutes les pages et donc il est très difficile de tester un emplacement particulier, et donc il y aura facilement des améliorations et des régressions, et pour ça, il faut revoir toutes les pages à chaque changement de paramètre (et il y en a une petite dizaine qui se croisent).

**Comment by alexis-michaud** [comment]
**wontfix** : suite aux tests menés par @BenjaminGalliot : paramètre à régler sur une échelle de 1 à 4, à 3 les orphelines restent, à 4 chaque entrée commence une nouvelle colonne.
