### ISSUE TITLE
dictionnaire : affichage liens DOI

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#115]
Petite régression à l'occasion de l'adoption des nouvelles polices en remplacement de Symbola, semble-t-il ? 
![image](https://github.com/user-attachments/assets/b6f488a7-48e6-4179-9507-dc877131b8ef)

Code : 
```
\txt Housebuilding2.300
\doi 10.24397/pangloss-0004550#S300

```

![image](https://github.com/user-attachments/assets/61ba0838-8cc6-46fd-8050-76a0b067f1f8)

**Comment by BenjaminGalliot** [comment]
Ah, oui, j’avais oublié ce détail !

![Copie d'écran_20241121_231433](https://github.com/user-attachments/assets/7f66b494-2e3f-40a5-9f9b-1c803450a2a2)

**Comment by alexis-michaud** [comment]
La typographie des numéros en rouge est classe ! :+1: Magnifique.
