### ISSUE TITLE
dictionnaire : un code langue à ajouter à général.xsl

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#116]
Ajout des infos pour la langue japhug : 

```
        <terme expression="jya">
            <traduction langue="cmn">茶堡话</traduction>
            <traduction langue="fra">japhug</traduction>
            <traduction langue="eng">Japhug</traduction>
        </terme>

```

C'est pour les comparanda japhug : affinage d'un ancien commentaire (note)
```
\nt <dom="comp" langue="fra"> Cf. japhug |fv{zɯɣ.tɕʰɤl}.
\nt <dom="comp" langue="eng"> See Japhug |fv{zɯɣ.tɕʰɤl}.

```
en : 
`\comp <langue="jya"> zɯɣ.tɕʰɤl`

Pour l'instant ça ne concerne qu'un seul exemple (hum). Mais ainsi ça ouvre un espace pour ajouter progressivement les comparanda japhug à l'avenir, en bon ordre.

Merci bcp !

**Comment by BenjaminGalliot** [comment]
C’est ajouté, mais je n’ai pas vu les lignes en question.

**Comment by alexis-michaud** [comment]
Magnifique ! 
![image](https://github.com/user-attachments/assets/dc0b87a2-01f9-48cc-8399-4fda7e169530)
Dans la version du jour de na.lex, c'est en ligne 5836

```
\lx bv̩˧ʈʂʰv̩˧
\sf <nb="B"> 652
\sf <nb="2011"> 976
\or bbuchu
\bw <langue="bod"> sbug chal |tib{སྦུག་ཆལ་}
\ps n
\lc bv̩˧ʈʂʰv̩˧
\sd <langue="fra"> musique
\sd <langue="eng"> music
\comp <langue="jya"> zɯɣ.tɕʰɤl

```
