### ISSUE TITLE
dictionnaire : remplacer "Étymologie : (<nom de langue>)" par "Étymologie : (emprunt <nom de langue>)"

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#117]
**Traitement des emprunts :** 
La version 1.2 du dictionnaire n'avait pas de typographie bien au point pour les mots d'emprunt. Ce qui apparaissait dans le PDF c'était la mention contenue dans les champs de définition. Ca fluctuait pas mal : parfois mention "emprunt chinois" dans la définition en chinois, parfois mention "emprunt" dans la définition en français.
![image](https://github.com/user-attachments/assets/5f738fe6-ea25-43b7-8024-7947dc9fe6ab)

![image](https://github.com/user-attachments/assets/8b2c94e2-873e-4d01-8ac4-b40b00de3bdf)

L'encodage a maintenant bien progressé. C'est proprement encodé, et il y a une bonne base pour un rendu impeccable.

Pour le dictionnaire en version chinoise, c'est bon : on y est.
![image](https://github.com/user-attachments/assets/ea856e1f-129f-4b95-800d-be4b6ddcd05a)
C'est clair, et c'est classe ! 

En version française et anglaise, il reste à améliorer. Dans le choix de l'affichage, actuellement, c'est : 
"Étymologie : (<nom de langue>)" 
![image](https://github.com/user-attachments/assets/512e35a0-f0ee-475c-841a-10bb04f4c5eb)

![image](https://github.com/user-attachments/assets/4107ec7f-c633-4ea6-a617-af60b72cc674)

Du coup, l'information "emprunt" (qu'encode le champ `\bw`) n'est pas explicitée.

C'est élégant de confier bcp d'informations à une typographie rigoureuse. Mais en l'espèce, il manque quelque chose, et il faut vraiment ajouter la mention "emprunt". 

Certes, c'est de l'ordre de l'étymologie, les emprunts, effectivement : c'est de là que ça vient (origine). Pour autant, indiquer un mot d'emprunt, Guillaume J. confirmera, je crois, que ça n'est pas exactement ce à quoi on s'attend quand on parle d'étymologie : l'étymologie revient plutôt à reconstruire le cheminement d'une forme au fil du temps, généralement dans la transmission d'une langue plus ancienne à une langue plus moderne (ou contemporaine).

D'où la proposition / demande :
remplacer "Étymologie : (<nom de langue>)" par "Étymologie : (emprunt <nom de langue>)"

En français : 
(emprunt `<nom de langue>`)
ce qui donnera : 
Étymologie : (emprunt chinois)
Étymologie : (emprunt txbxtxn)
Étymologie : (emprunt naxi)
etc.

En anglais, même changement : 
(`<nom de langue>` loanword)
ce qui donnera (après le préfixe du bloc étymologique, inchangé) : 
(Chinese loanword)
(Txbxtxn loanword)
(Naxi loanword)
etc.

(En chinois, rien à changer, comme indiqué ci-dessus.)

Merci bcp !

**Comment by BenjaminGalliot** [comment]
C’est fait !
