### ISSUE TITLE
dictionnaire : un lien du pied de page à corriger

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#118]
Les liens en pied de page sont un luxe somptueux pour la consultation et la navigation ! Le bonheur. 

Dans la série des rimes, ɑ ɑ̃ æ æ̃ e ɤ ə i ĩ o õ ɻ ̩ ɻ ̩̃ u ɯ v̩ ṽ̩, il y en a une seule qui fait des siennes : 

![image](https://github.com/user-attachments/assets/b88fb4f5-207b-40af-9342-b84708c1e97a)

Le ɻ ̩̃  pointe sur la Table des matières : comportement typique de lien non trouvé.

Une piste : cela tiendrait à l'ordre dans lequel apparaissent les deux diacritiques. 

À un moment une idée c'était de tout prévoir, pour que dans les cas où il y a un rendu similaire à l'œil mais avec une séquence Unicode sous-jacente différente, Lexika gère avec autant d'efficacité que de discrétion. Mais une bonne vieille règle simple et claire de derrière les fagots constitue un repère bien utile et du coup c'est sur ça qu'on est désormais parti. Tout indique (me semble-t-il) que cette orientation est gérable et fonctionnelle. 

L'ordre auquel j'essaie de me tenir, histoire de ne pas avoir des variantes à gérer à toutes les étapes, c'est le même pour les deux symboles qui ont ces 2 diacritiques :
ṽ̩ : v puis la nasalité   ̃ et en dernier le tiret souscrit   ̩ 
ɻ̩̃: ɻ puis la nasalité   ̃ et en dernier le tiret souscrit   ̩ 

Ca commence à être rodé. Mais l'application bien cohérente de cette convention est récente (2024) et il se pourrait qu'il traîne dans les fichiers de configuration de Lexika des scories d'époques anciennes (dont je suis 100 % responsable) qui sont à écarter.

**Comment by alexis-michaud** [comment]
Ce petit souci est lié à un autre : la rime ɻ̩ nasalisée ( ɻ̩̃ ) n'a pas son chapitre à elle. Elle apparaît dans le chapitre de la lettre ɻ c'est-à-dire de la consonne **initiale** ɻ 

![image](https://github.com/user-attachments/assets/85db123f-8670-4299-a17c-05c5a53f8b84)

![image](https://github.com/user-attachments/assets/82e8d526-fb0b-41c4-b474-256aa1d42838)

Pareil pour le ṽ̩ qui se trouve dans un chapitre "mutualisé" avec v̩ 
![image](https://github.com/user-attachments/assets/7d5fdbf0-866b-4d34-9a63-fde1c17bafdc)

**Comment by BenjaminGalliot** [comment]
Problème réglé, c’était effectivement le fichier de configuration et la liste inférieure qui avaient un graphème avec des diacritiques dans un ordre différent.
