### ISSUE TITLE
dictionnaire : traduction en français de l'indication "Suite en page suivante"

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#119]
Pour le chinois, la traduction de la double indication pour les tableaux répartis sur plusieurs pages a été faite et bien faite depuis un bout de temps.
![image](https://github.com/user-attachments/assets/4abe374d-29e8-46b9-8ca9-d7336ea51445)

Pour le français, cela reste-t-il à faire ? Je ne suis pas tout à fait sûr. 

Quand je compile en local, avec une version de Lexika installée le 10 novembre 2024, les indications sont en anglais. 
![image](https://github.com/user-attachments/assets/cbe94025-4e03-46cd-a8f9-64c6bdab7c1d)

Mais dans la version du 22 novembre 2024 que tu m'as envoyée, le cas de figure ne se présentait pas. Du coup je ne sais pas si le ticket est nécessaire. On verra bien dès la prochaine compilation sur ton ordinateur après mise à jour des fichiers `.tex` de l'introduction ([ici](https://github.com/alexis-michaud/na/tree/master/DICTIONARY/introduction)) : le cas de figure devrait se présenter pour le tableau 1.

Merci bcp !

**Comment by BenjaminGalliot** [comment]
Bien vu, j’avais fait la traduction uniquement pour le chinois !
