### ISSUE TITLE
dictionnaire : tilde dans le champ \va

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#121]
Le tilde, c'est vraiment pas une mince affaire, comme tu (@BenjaminGalliot ) le relevais ! 

Le bogue du jour : il est tout mignon, c'est que le champ `\va` se retrouve émondé de ses tildes. Par exemple : 
```
\va <speaker="F4"> ə˧-ze˧~ze˥
\va <speaker="M21"> ə˧-zɤ˧~zɤ˥

```
donne le rendu suivant :
![image](https://github.com/user-attachments/assets/6ceff7dd-f9b5-4559-a97a-0541c790ba4c)

C'est tout bon... mais le tilde n'y est plus. Il est interprété comme une espace (ce qui est bien normal dans LaTeX). Lexika doit faire quelque chose pour lui pour le protéger.

(Juste pour info : je viens d'ajouter une ligne dans `na.lex`, c'est vers la ligne 15547)
```
\va <speaker="F4"> ə˧-ze˧~ze˥
\va <speaker="F5"> ID.
\va <speaker="M21"> ə˧-zɤ˧~zɤ˥

```

**Comment by alexis-michaud** [comment]
(pour rappel, le tilde signale une forme rédupliquée)

**Comment by BenjaminGalliot** [comment]
Ce problème touchait les variantes mais aussi quelques formes de surface (et surtout les `#`). C’est corrigé. Je viens aussi de prévoir le même comportement pour les orthographes le cas échéant ultérieurement (mais ça ne change rien pour le moment).

![Copie d'écran_20241202_174600](https://github.com/user-attachments/assets/840dbccc-d33b-4bd4-86e0-291cd51f7b2f)
