### ISSUE TITLE
dictionnaire : ajouter un symbole devant l'information "Synonyme", afin de démarquer du champ précédent ?

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#122]
Dans la version française du dictionnaire, le lien indiqué comme "Synonyme" n'est pas précédé d'un symbole particulier. 
Dans les cas où c'est précédé par un bloc nettement distinct, par exemple du chinois, ça rend très bien : comme dans la première des deux entrées ci-dessous. En revanche, quand c'est du français qui précède, ça donne un peu l'impression d'une 'ourlet' manquant, non ? (Dans le bas de l'image ci-dessous) 
![image](https://github.com/user-attachments/assets/c72b53fd-0049-473b-9c7c-8a8ef161bad7)

Cela tient au fait qu'une note / commentaire en français vient s'insérer entre le bloc des définitions et le lien "Synonyme".

Ce cas est marginal, mais il en existe quelques cas
![image](https://github.com/user-attachments/assets/2c86c865-6e8b-4cb3-9612-ab6983169385)

et on souhaite au dictionnaire de contenir de plus en plus d'informations de type `\sy` au fil de son développement futur. 

Il y a déjà une espace plus longue devant le champ "Synonyme", qui assure la démarcation au plan fonctionnel. Si on cherche la petite bête (et la Beauté typographique, toujours plus raffinée !), ça n'est pas complètement absurde de se dire que ça pourrait valoir la peine de faire un aménagement : ajouter un chouette :owl: symbole devant "Synonyme". 

Ca n'est absolument pas prioritaire sur quoi que ce soit, et ça peut parfaitement attendre une future version. Ce que je pourrais faire pour bricoler en attendant, dans les quelques cas concernés, ce serait de veiller à ce qu'il y ait un point final en fin de note/commentaire, ce qui compléterait la démarcation avec le "`Synonyme : `" qui suit.

**Comment by alexis-michaud** [comment]
Peut-être l'un des symboles suivants pourrait-il revenir dans la course ?
▣
☉
❊

Forte préférence pour le symbole ▣. Il ressortirait bien, un gros démarcateur : comme un bloc de béton bien compact posé en travers d'une chaussée, qui ne se laisse pas oublier :smiley: Cela mettrait en valeur la présence de cette info "Synonyme". 

Le symbole ☉ paraît attirant parce qu'il est nettement distinct mais je ne sais pas du tout si à la mise en œuvre ça donnerait quelque chose d'intéressant : peut-être trop cabalistique et intrigant. Comme un symbole qui s'insère dans le flux de la ligne, comme s'il contenait une info à lire, plutôt qu'un démarcateur.

Le symbole ❊ ferait pâle figure à proximité de 🟔, les deux ne feraient pas bon ménage, me semble-t-il (juste des idées comme ça).

**Comment by alexis-michaud** [comment]
Le même symbole apparaîtrait devant "Antonyme", "Voir aussi"...

Au cas où on en aurait déjà parlé et on aurait convenu de ne pas ajouter de symbole, pas de souci : je n'ai plus la mémoire de cet échange précis bien claire (est-ce que l'idée d'avoir plein de symboles cabalistiques a été envisagée puis écartée ?), et m'en remets bien sûr à tes décisions & aux orientations de Lexika. Il ne s'agit pas que j'introduise des régressions, à 1 semaine de la mise en ligne, en changeant d'avis comme de chemise. La mise en page est déjà bien comme elle est actuellement.

**Comment by alexis-michaud** [comment]
Si on me demande mon avis, je trouve que ça fait trop de symboles identiques, comme une pluie de flocons de neige. Ca donne l'impression d'une segmentation des entrées en "tranches" indistinctes. 

L'emploi de ▣ donnerait plus d'étoffe aux entrées, en signalant visuellement la diversité des informations, qui ne sont pas simplement des éléments concaténés avec séparateur mais constituent des infos tirées de champs différents.

**Comment by alexis-michaud** [comment]
Pour partir sur un symbole-pointeur (en cohérence avec la sémantique d'un lien vers autre chose), tout en restant bien distinct du pointeur vers la droite ► qui introduit le bloc de définitions, que dirais-tu d'un petit triangle pointant vers la droite ? 
▸
Il serait composé dans une couleur bleue
Entre le triangle plein et le triangle vide (▹) je n'ai pas trop idée de ce qui rendrait bien. Le fait d'utiliser un symbole vide pourrait être pas mal pour mieux le distinguer du triangle qui introduit la définition ? 
Troisième possibilité, un triangle vide plus grand
▷

**Comment by BenjaminGalliot** [comment]
![Copie d'écran_20241202_201957](https://github.com/user-attachments/assets/19f4ea9d-6115-4db1-8b3a-4ceeff857839)

Voilà ce que ça donne avec la police Noto Symbols 2.

**Comment by BenjaminGalliot** [comment]
Bien, partons sur le ▣, je n’ai rien contre, après tout !
