### ISSUE TITLE
dictionnaire, version anglaise : un tout petit détail : espace après un point .

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#126]
En typographie anglaise, l'espace après un point final de phrase est un peu plus longue, par une convention qu'applique, du coup, "Lexika".

De ce fait, les points à l'intérieur d'une phrase sont aussi suivis d'une espace longue, ce qui n'est pas souhaité. 
![image](https://github.com/user-attachments/assets/3c5746ee-1ca4-4abe-8d47-7a8c33947227)

Une façon de traiter ça dans LaTeX consisterait à utiliser des commandes spéciales. 

Une autre consisterait à protéger chaque espace après le point par une commande `\ `.

Au jour d'aujourd'hui il y a une trentaine de "i.e." dans le PDF (34 dans na.lex), pas mal de "e.g." (103 dans na.lex), et quelques "Mrs." ("Mrs. Latami") et deux "Mr.".

Ca ne me paraît pas bien gênant (y'a pas lieu de retarder la sortie de la version 2.0 pour ça), mais je voulais le signaler au cas où tu jugerais bon de mettre en place un traitement pour ces quelques cas. 

Un intérêt de le traiter dans Lexika, d'une façon invisible aux utilisatrices & utilisateurs, est que ça serait d'autant plus systématique. Ainsi pas de risque que, dans une saisie de données qui s'étale sur des années & des décennies, ne soient introduits des cas de saisie "en dur" d'un _e.g._ ou d'un _i.e._ alors que la pratique convenue serait d'utiliser `\eg` et `\ie`. Il pourrait aussi y avoir un avertissement à la compilation ("Recommandation: remplacer i.e. par une commande...") mais tant qu'à repérer ces cas dans Lexika, autant les traiter 100 % en interne ? 

Existe-t-il des scripts déjà rodés qui rendent les services attendus pour un échantillon raisonnable d'abréviations? Parmi celles que je n'utilise pas mais qu'on croise de temps à autres, il y aurait _viz._, _a.m. / p.m._ pour matin et après-midi...

Dans l'attente de tes (@BenjaminGalliot ) instructions

**Comment by BenjaminGalliot** [comment]
D’après différentes sources, il vaut mieux partir pour l’usage d’une seule espace après le point en anglais…

https://en.wikipedia.org/wiki/Sentence_spacing
https://www.grammarly.com/blog/punctuation-capitalization/spaces-after-period/
https://www.thesaurus.com/e/writing/is-there-1-space-or-2-after-a-period/
