### ISSUE TITLE
dictionnaire : traitement code langue xina1239 pour les emprunts

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#127]
Les emprunts au chinois local (mandarin du Sud-Ouest) ont comme indication de langue le code Glottolog : xina 1239
Il n'y a que quatre exemples à ce jour.
![image](https://github.com/user-attachments/assets/d53523a1-b9eb-4e08-9135-b09e2a6eac5b)

C'est tout de suite plus clair avec un exemple mimi (mais non marchand) : 
![image](https://github.com/user-attachments/assets/02d7cae8-3cb3-46b1-af67-ffee820066fc)

Pour le rendu, en plus du code couleur pour les caractères chinois (qui est impeccable), serait-il possible d'indiquer les infos suivantes ?
mandarin du Sud-Ouest
Southwestern Mandarin
西南官话

ce qui, dans la belle mécanique Lexika, donnerait normalement :
(emprunt mandarin du Sud-Ouest)
(Southwestern Mandarin loanword)
（西南官话借词）

Merci beaucoup !

**Comment by BenjaminGalliot** [comment]
C’est corrigé, il suffisait d’ajouter sa traduction dans la liste habituelle !
