### ISSUE TITLE
dictionnaire : plan de nommage des fichiers pour dépôt HAL

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#132]
En lien avec #128 :

Pour le nommage des fichiers .lex et .xml : ça pourrait être pas mal d'intégrer à la convention de nommage le numéro de version. Par exemple : na_v2.lex et na_v2.xml.

Pour le nommage des fichiers PDF : na_fra.pdf, na_eng.pdf et na_cmn.pdf est une bonne base pour nous et on s'y retrouve bien (en bricolant: de mon côté j'ajoute une date), mais pas forcément pour un fichier dans HAL. 

Language Science Press a un nom de fichier pas méchant mais un peu code-barre quand même : 
109-Book Manuscript-652-1-10-20170425-3.pdf
(En plus "Manuscript" est plutôt trompeur, tu ne trouves pas, pour désigner un PDF publié en bonne et due forme, une version de référence ??)
Bon, ça marche, c'est bien, rien à dire... mais sur ce point Lexica peut faire mieux que LangSciPress :1st_place_medal: 

Pour le français je verrais bien quelque chose de sobre et clair, comme 
`<TitreAbrégé>_Lexica_<numéro dans la collection Lexica>_v<numéro de version>.pdf`
Ce qui donnerait : 
`DictionnaireNa_Lexica_3_v2.pdf`
(ou si tu préfères : `Lexica_3_DictionnaireNa_v2.pdf`, pas de souci)

Pour l'anglais, on se calquerait sur le français : 
`NaDictionary_Lexica_3_v2.pdf` (ou `Lexica_3_NaDictionary_v2.pdf`, pas de souci)

Pour le chinois ça serait nettement mieux d'avoir un nom de fichier en chinois, et qui reprenne le titre :
`永宁阿拉瓦村摩梭方言—汉—英—法词典_2.pdf`
Pour des raisons diplomatiques importantes, il faut qu'apparaisse la longue séquence 永宁阿拉瓦村摩梭方言 "dialecte du village de Alawa, de Yongning" (déjà j'ai ferraillé pour expliquer que Non il ne fallait pas préciser "... du **canton** de Yongning", le terme administratif du moment : ça devenait vraiment trop long, et puis cette terminologie change souvent, cf. note 2 page xi de l'édition en chinois, version du 25 novembre). Des gens d'autres endroits de l'aire linguistique concernée (Lataddi, au bord du Lac, en particulier) pourraient s'offusquer (gravement) qu'on présente comme "dictionnaire na", sans précision, un dictionnaire qui n'est "que" celui d'un parler particulier d'un certain village qui n'est pas le leur (telle variété de la langue na **de Yongning**), qui est situé dans une autre province (l'aire na est à cheval entre Yunnan et Sichuan), parlée par des gens qui dans la nomenclature officielle ne font pas partie de la même "nationalité", etc. Tu vois l'idée.

C'est long, ce titre chinois, ce qui ne laisse pas beaucoup de place pour "Lexica". Mais si le nom chinois de Lexica & Lexika n'est pas encore super-stabilisé, ça pourrait être une raison de ne pas le faire figurer dans une convention de nommage.

S'il était souhaitable d'abréger (pas de noms de fichiers qui fassent des kilomètres), ça irait dans le sens de dire : 
`永宁阿拉瓦词典_2.pdf`
("dictionnaire de Yongning-Alawa")
mais il serait vraiment de loin préférable d'avoir un titre complet comme proposé plus haut (`永宁阿拉瓦村摩梭方言—汉—英—法词典_2.pdf`).

**Comment by BenjaminGalliot** [comment]
Lexika 3 Dictionnaire na v2 2024-12-06.xml
Lexika 3 Na Dictionary v2 2024-12-06.xml
Lexika 3 永宁阿拉瓦村摩梭方言—汉—英—法词典 v2 2024-12-06.xml
