### ISSUE TITLE
dictionnaire : finalisation couvertures pour la version 2

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#133]
Couverture chinoise : 
- modification du nom de Lexica : 世界珍稀语言系列词典丛书
- modification du nom de Mme Latami : 拉它米打史拉姆 à remplacer par 拉他咪打史拉姆 (changement des trois premiers caractères). 
- modification du nom de Pascale-Marie Milan en chinois : 瑸妈拉姆 à remplacer par 皮艾木
- modification de mon nom en chinois : une personne proche du dossier souligne que pour la couverture et les métadonnées, il faut s'en tenir au nom chinois qui est le mien, 米可, sans y ajouter un nom qui au fond n'est jamais utilisé sauf entre moi et ma prof (et encore, bien rarement, comme une sorte de clin d'œil).
Autrement dit, remplacer dans les métadonnées de la version chinoise (et d'ailleurs)
**一史棣嘟（米可）（Alexis Michaud）**
par : 
**米可（Alexis Michaud）**

Couverture anglaise et couverture française (1e de couverture et 4e de couverture) : quand il y aura une version de prête, je serais preneur pour regarder.

Pour rappel, le texte pour la quatrième de couverture est dans le même dossier que les résumés pour HAL, la préface et l'introduction. Le fichier `blurb` concerne spécifiquement le dictionnaire na ; le fichier `Lexica_blurb` concerne la collection Lexica.

Merci bcp !

**Comment by BenjaminGalliot** [comment]
C’est corrigé pour les pages de titre et d’informations, ainsi que dans les métadonnées (il n’y avait que ton nom et celui de Pascale-Marie à mettre à jour).

Je regarderai demain pour la couverture.

**Comment by alexis-michaud** [comment]
alles klar
