### ISSUE TITLE
dictionnaire : page d'informations

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#135]
Contributions : 
![image](https://github.com/user-attachments/assets/2d42be8d-b98c-48d3-b6d4-ec094f8d228f)
@BenjaminGalliot Tu m'as expliqué le souci d'exhaustivité. Mais au bilan, je trouve que dans la liste, "réalisation des photos de couverture" paraît anecdotique en comparaison des autres. Je trouve que ça donne un air d'inventaire à la Prévert. 
Est-ce qu'il n'est pas courant de fournir les infos concernant la couverture de façon séparée, quitte à répéter les noms?
Serait-il possible de garder la mention en bas de page 
![image](https://github.com/user-attachments/assets/aeeea85f-9508-4691-a7c9-8bb074389416)
et de ne pas en faire mention dans le bloc "Auteurs" ?
(Que ça ne t'empêche pas de mentionner la conception de la couverture parmi tes attributions : c'est pas vraiment de même nature que simplement fournir des photos.)

J'aimerais également que soit retiré "traduction". Là aussi je comprends la logique : essayer de caractériser tous les "actes" qui ont été réalisés pour le dictionnaire. Mais je trouve que c'est d'autre nature, la traduction : si je traduis quelque chose (par exemple la post-face), c'est indiqué dedans. Une mention ici laisserait croire que c'est du dico qu'il s'agit. 

Ca donnerait : "collecte et compilation des données, recherche linguistique, rédaction"

Pour Mme Latami : difficile ! 
Tu proposes "informatrice-locutrice". Renvoyer, dans la page des informations, quelqu'un à qui est accordé le statut de co-autrice à un statut "informatrice-locutrice", ça ressemble à un camouflet, une façon de dire "co-autrice, mais en fait non : informatrice-locutrice".

C'est bancal, si c'est à titre d'informatrice-locutrice qu'elle figure. Pourquoi elle et pas les autres ? 

Entre le terme ancien "informateur" (qui a le défaut d'être aussi utilisé pour les "indics" de la police) et l'anglicisme "consultant linguistique", qui se répand et le remplace, ma préférence va à "consultante linguistique" (en anglais "language consultant"). J'avais adopté ça dès ma thèse, de préférence à l'usage ancien (respectable, et que Michel Launey, de la génération précédente, utilise encore, par exemple). Mais même enrichi du qualificatif positif "consultante linguistique principale", ou "consultante linguistique de référence", le compte n'y est pas. 

Qu'est-ce qu'il y a d'autre dans la nomenclature adoptée par Lexica ? 

Pour essayer de décrire les choses : justement la reconnaissance du statut de co-auteur est une façon de mettre en avant le fait que c'est sur elle que reposent toutes les informations. C'est elle _l'autorité_ pour le contenu, pas simplement par une décision arbitraire (extérieure) qui lui prête le statut de locutrice de référence, mais par acceptation de participer au travail, par choix de faire les choses bien, et, au fil des années, par plaisir / désir d'y être associée (enfin c'est moi qui le dis). 
Tu vois, la mise au point du dictionnaire ne se fait pas simplement 'en aval' de sessions de travail qu'on réaliserait ensemble. Cette année on a revu ensemble le dictionnaire page par page. Là on voit ce dont il s'agit, l'ordre lexicographique avec ce qu'il a de cocasse, les exemples "de dictionnaire", les mots qui manquent, les renvois... C'est autre chose que de fournir des infos "brutes" (sortes de "matières premières") qui seraient ensuite travaillées séparément par la team #Chercheurs (Pascale-Marie et moi). L'entreprise de documentation est une entreprise commune, dont elle ne ressent pas moins que moi la nécessité et l'utilité. 

Elle n'a pas été "écolée" et ne pratique donc pas l'écrit, mais c'est quelqu'un d'érudit, une érudite en matière de tradition orale. Elle est fin connaisseur de la langue et de la tradition orale. Elle est d'une génération qui parle nettement "mieux" que les plus jeunes, et au sein de sa génération, elle était particulièrement attentive et observatrice et garde en tête des choses dont bcp d'autres ont perdu la mémoire. Quand son fils la décrit comme "directrice de recherche" (导师), c'est à ça qu'il fait référence : une forme d'autorité qui est celle d'un _mentor_. Mais mettre "à froid" dans des mentions légales un titre employé de façon métaphorique, c'est un drôle de mélange des genres.

L'exercice n'est pas facile, pour éviter les chausse-trapes : que la page des infos n'ait pas trop un effet "lit de Procuste". Une nomenclature peut rendre des services, mais standardiser, calibrer, catégoriser, ça porte un risque de se faire au détriment de la nuance. Une expression juste se fait via un récit et non via un référentiel. C'est une relation humaine qui chez les Na (comme on peut le lire dans la préface de Dashi) a une allure familiale : une sorte d'intégration à la famille. J'ai eu d'emblée consigne de l'appeler "Ama" /ə˧mɑ˧/, ce qui implique une insertion dans une relation où la succession des générations joue un rôle fondamental. Ce n'est pas juste moi qui la "fais parler", c'est une chaîne de transmission originale et créative qui se met en place dans un schéma où les "savants" (chercheurs) ne le sont pas mais essaient au contraire de s'élever, à la force du poignet, vers les savoirs des Na, guidés par eux (pour moi : essentiellement par elle).

Tu insistes sur le caractère "légal" des infos sur cette page ("mentions légales", "déclaration légale"). Une nomenclature se doit d'être "objective", froide et factuelle : les mentions légales ne sont pas un genre littéraire. Mais ça ne me paraît pas correct de traiter Mme Latami comme ça. Un descriptif dans des catégories "lit de Procuste" (même/surtout un lit "bien propre") ne ferait pas l'affaire, la vérité étant dans le récit (à mes yeux). J'ai le sentiment que ça se fait pas, pour le propos légal d'une page d'infos, d'inventorier les qualités (et, en creux, les limites de l'apport) de quelqu'un qui apporte au projet avec beaucoup de générosité et de finesse. Ca me paraît une limite de cette page d'informations.

Bon, pour avancer tout de même malgré ces résistances vivaces, et "trancher le nœud gordien" : un descriptif comme : 

"Connaisseur de la langue et la tradition orale na. Locutrice de référence et collaboratrice dans l'entreprise de documentation" 
? 
`eng` Connoisseur of the Na language and Na oral traditions. Reference language consultant and collaborator in the documentation work.

Pour Pascale-Marie : 
"recherche anthropologique, rédaction"

**Comment by BenjaminGalliot** [comment]
Je comprends parfaitement le problème en question, et c’est pour cela que je disais sur le site de la collection qu’on s’inspirait de ces recommandations et nomenclature. Rien n’empêche donc qu’on prenne des libertés et qu’on affine ça prochainement et durant les versions successives pour avoir des rôles plus en rapport avec notre discipline.

![Copie d'écran_20241202_001550](https://github.com/user-attachments/assets/ac38e993-0629-4a97-86de-c8c1d6e1558f)

**Comment by alexis-michaud** [comment]
Ca marche. Normalement ce ticket peut être clos (je te laisse gérer).

Sur le ticket #133, il y a des infos qui concernent la page d'informations aussi bien que les couvertures (noms en chinois pour 3 des auteurs).

Merci bcp
