### ISSUE TITLE
[dictionnaire] affichage des commentaires

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#14]
Parmi les infos du fichier na.lex qui pour l'heure ne sont pas affichées dans le fichier PDF : 

* informations concernant les classificateurs les plus couramment associés à un nom : sa forme (en phonétique, éventuellement aussi en orthographe), et le type d'interprétation auquel ce classificateur est associé. Exemple :
```
\pdl classifier
\pdv kɤ˧˥
\pdc <langue="fra"> pour le grain
\pdc <langue="eng"> for paddy rice
\pdc <langue="cmn"> 用来指稻子
\pdl classifier
\pdv pʰæ˧˥
\pdc <langue="fra"> pour les champs
\pdc <langue="eng"> for paddy fields
\pdc <langue="cmn"> 用来指稻田
```
La syntaxe actuelle est : 
`["Classificateur courant : ",<forme_du_classificateur>]`
ce qui donne par exemple, dans l'entrée "Mouton", /jo˩/ : **Classificateur courant : pʰo˧˥**
La mise en forme typographique, dans le cas où il y a deux classificateurs ou plus, pourrait être la suivante : 
`["Classificateurs courants : ",<cas1>," : ",<forme_du_classificateur_dans_le_cas_1>,<cas2>," : ",<forme_du_classificateur_dans_le_cas_2>]` etc.

par exemple pour l'entrée "riz paddy" : 
```
\pdl classifier
\pdv kɤ˧˥
\pdc <langue="fra"> pour le grain
\pdc <langue="eng"> for paddy rice
\pdc <langue="cmn"> 用来指稻子
\pdl classifier
\pdv pʰæ˧˥
\pdc <langue="fra"> pour les champs
\pdc <langue="eng"> for paddy fields
\pdc <langue="cmn"> 用来指稻田
```
 **Classificateurs courants : pour le grain : kɤ˧˥ ; pour les champs : pʰæ˧˥**
En chinois : 【 量词】kɤ˧˥（用来指稻子），pʰæ˧˥（用来指稻田）

* pour les exemples: champ d'origine, `\rf` (locutrice/locuteur ayant fourni l'exemple). Pour l'instant (10/2023), le champ d'origine ne s'affiche pas. Dans les exemples, le regard bute à chaque fois sur des bizarreries, qui sont en fait des différences entre idiolectes. Le contenu du champ est un code locuteur, à afficher avec les codes choisis en 2024 avec @BenjaminGalliot (fournis dans le tableau en introduction du dictionnaire).

* également pour les exemples : champ de commentaire, `\xc`. Syntaxe : après la traduction de l'exemple, entre crochets carrés ? ou entre simples parenthèses ?

* également pour la catégorisation des exemples : certains, fruit d'une élicitation (morpho-)phonologique, portent la mention "phono" (`\xc PHONO`). Ils sont à composer dans le PDF avec la mention (en chinois)`（音系资料）` en début d'exemple. Exemple dans la version 1.2 du dictionnaire : 
![image](https://github.com/alexis-michaud/na/assets/6072524/a87fbe0c-33b8-44c2-9954-da583b02d035)
D'autres portent la mention PROVERBE.
D'autres sont en champ libre.

**Comment by DuMeigui** [comment]
\or ge  
\or pae
;-)

**Comment by alexis-michaud** [comment]
> \or ge \or pae ;-)

Yes, it would be good to have the orthographic form of the classifier(s) (in this case, respectively `\or ge` and `\or pae`), especially for an orthography-centered version of the dictionary.

**Comment by alexis-michaud** [comment]
Ｔraité dans la version du 7 mai
:+1: @BenjaminGalliot

**Comment by alexis-michaud** [comment]
![image](https://github.com/user-attachments/assets/898e7626-769f-4ee6-b932-4112f46bd542)
:+1:
