### ISSUE TITLE
Lexica / dictionnaire : harmonisation entre page de titre intérieure et page de métadonnées

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#140]
La page de métadonnées, "qui fait foi", dans la logique suivie au fil du travail de finalisation, porte, dans la version anglaise, les infos suivantes : 
Lexica Collection:
• Benjamin Galliot (區勄狐): collection director and IT supervisor;
• Guillaume Jacques (向柏霖): scientific supervisor.
![image](https://github.com/user-attachments/assets/12efb8e4-d266-4936-8713-066f5df139b9)

En revanche, pour l'heure, la page de titre intérieure porte la mention : 
Collection Lexica
Collection director and IT responsible
Benjamin Galliot（區勄狐）
Scientific responsible
Guillaume Jacques（向柏霖）
![image](https://github.com/user-attachments/assets/cf4eb7e0-c6a6-4f44-9733-78e43d804da5)

Or en anglais, comme on en avait sans doute discuté lors des échanges au sujet de la page des métadonnées, "responsible" est un adjectif et ne se prête pas à un emploi comme substantif ("le responsable").

Il faudrait donc harmoniser la page de titre intérieure en fonction des métadonnées de la page des "infos légales".

(Au passage, un commentaire : pour la version anglaise, écrire "Lexica collection" ou "Lexica series" plutôt que "Collection Lexica" me paraîtrait pas mal, mais ça c'est juste une idée / suggestion à débattre par l'équipe de Lexica, bien sûr.)

**Comment by BenjaminGalliot** [comment]
Bien vu ! Ça ne m’étonne pas, la version anglaise a forcément eu un peu moins de vérifications…

**Comment by alexis-michaud** [comment]
À modifier dans `latex alphabétique anglais.xsl`, lignes 203 à 209
```
    \textegrisé{Collection director and IT supervisor}

    \textbf{\plettresstylisées{\benjaminfra}}（\textbf{\textecmncn{\benjamincmn}}）

    \bigskip

    \textegrisé{Scientific supervisor}

```
Je ferme ce ticket. @BenjaminGalliot souhaites-tu que j'en ouvre un dans le dépôt Lexika, pour mémoire ? (afin que la modif' soit intégrée au code Lexika)

**Comment by BenjaminGalliot** [comment]
Pas besoin, je le ferai pour la prochaine mise à jour.

**Comment by alexis-michaud** [comment]
Le rendu visuel peut être vérifié ici : 
https://github.com/alexis-michaud/na/blob/master/DICTIONARY/PDF/Lexika_3_NaDictionary_v2_0_1_2024-12-28.pdf
Version 2.0.1 dans toute sa splendeur !
