### ISSUE TITLE
[orthography] harmonizing: xe::ɕjɤ & xie::ɕi ?

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#16]
In most cases _xe_ corresponds to **ɕjɤ** and _xie_ corresponds to **ɕi**. Should it be harmonized, changing ɕjɤ˩tʰv̩˧˥ to _xetu_ instead of _xietu_? Or are there dialect considerations here (some dialects where they say ɕi.tʰv̩ for 骂)?

**Comment by DuMeigui** [comment]
Hi Alexis,


This one is a dialectic consideration. I suspect that the first morpheme is related "tongue".


Thanks for asking!

R 🌹


________________________________
