### ISSUE TITLE
[dictionnaire] indiquer en bas de page la séquence des caractères API (ordre de tri)

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#17]
En bas de chaque page. Ca permettra de se repérer plus facilement. 
La commande pour un pied de page c'est `\rfoot{text}` mais il faut gérer la position : il faudrait 2 lignes dans le pied de page, une pour le numéro de page (centré) et une pour la séquence des caractères API.
Pages impaires : indiquer les initiales, et pages paires : indiquer les rimes, si ça tient. Sinon, mettre la 1e partie des initiales sur les pages paires, et la 2e partie sur les pages impaires.

**Comment by alexis-michaud** [comment]
@BenjaminGalliot Est-ce que c'est imaginable dans la collection "Lexica" (peut-être même déjà implémenté ?) ?
Ou est-ce que ça n'est pas prévu dans la feuille de style, et on n'en parle plus ?

**Comment by BenjaminGalliot** [comment]
Salut, c’est imaginable, mais je ne sais pas à quel point c’est généralisable à tous les dictionnaires selon les particularités de chaque langue. Je peux jeter un œil dès que j’ai le temps et voir ce qui sera possible.

**Comment by alexis-michaud** [comment]
Si ça augmente le nombre de pages du dictionnaire, ça n'est pas un inconvénient en soi : c'est un luxe qu'on peut se permettre pour des langues qui ont moins de 10 000 entrées dans le dictionnaire, d'avoir une info redondante et un peu gourmande en espace, dès lors qu'elle rend vraiment un service. Pour un dictionnaire organisé selon un principe de tri qui n'est pas évident, c'est un élément de confort important.

**Comment by BenjaminGalliot** [comment]
Voilà un premier essai, qui était plus difficile que prévu à cause de la page de titre de chapitre (c’est connu dans le milieu qu’elle a toujours son propre style). Il a fallu faire une double redéfinition mais je crois que c’est bon, à voir quand ce sera terminé.

![Copie d'écran_20240910_182018](https://github.com/user-attachments/assets/13c0125d-228b-423c-b73b-09971c367069)

Après je sais que certains ouvrages mettent cette liste latéralement et verticalement…

**Comment by alexis-michaud** [comment]
Super !!!
Par contre, moi je ne mérite pas de compliments pour la consigne que j'ai fournie. Elle est rédigée en dépit du bon sens. "Pages impaires : indiquer les initiales, et pages paires : indiquer les rimes" : en fait j'avais en tête les consonnes (initiales) sur la page de gauche, et les voyelles (rimes) sur la page de droite, puisqu'une syllabe c'est consonne+voyelle, dans l'ordre de la lecture (de gauche à droite). J'ai écrit sans bien réfléchir : j'ai dû me mélanger les pinceaux en oubliant que la page de gauche c'est une page paire...

Bref, au temps pour moi : les initiales seraient à mettre sur la page de gauche (=page paire), et les rimes sur la page de droite (=page impaire). Vraiment désolé pour ce cafouillage dont je suis seul responsable...

**Comment by alexis-michaud** [comment]
Fait, merci Benjamin !
