### ISSUE TITLE
Chilli

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#18]
The dictionary contains references to both "chili pepper" and "chilly pepper". Clearly, "chilly" is incorrect. "Chili" and "chilli" are both acceptable. I prefer the latter, but in any case this needs to be sorted out.

R  :-)

**Comment by alexis-michaud** [comment]
Done! Many thanks!!
457998efe5c2174b6c72536f7894de1cb188e058
(and I gave a real-time demo to He Likun, who is here in LJG!)

**Comment by DuMeigui** [comment]
Cool!


________________________________
