### ISSUE TITLE
A few hyphens

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#22]
Hi Alexis,
For the following items, could you please insert a hyphen in front of the orthographic form, to indicate that these "words" are always written attached to another word:

-mi˩˧ /mi˩˥/ mi  Feminine suffix.    **-mi**

-di˩ /di˩˥/ ddi Nominalizer; locative or purposive.  **-ddi**

-hĩ˥ /hĩ˧/ hin  Relativizer and nominalizer.   **-hin**

-ɻ˩̍ /ɻ˩̍ ˥/ er  Inceptive (inchoative).   **-er**

=ɻ˩̍ /ɻ˩̍ ˥/ er  Associative plural. **-er**

Thanks!

**Comment by alexis-michaud** [comment]
Done!
Example below: 
![image](https://user-images.githubusercontent.com/6072524/39406856-e4e9fee4-4bef-11e8-9e21-2f2e41abbca2.png)
