### ISSUE TITLE
Back to mushrooms

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#25]
Sorry, Alexis, the "mushroom morpheme" needs a q on the end when it's written as a single word - my omission.  So:
aensheili mo**q** 
aenzi keezhe mo**q**
eliahaenshi mo**q**
yekhabeye mo**q**
zzeezzee mo**q**

**Also** (ones I overlook last week and have discussed with SGM already): 
**kiqi moq**  (not kiqimo)
**kuapu moq** (not kuapumo)

But not change for the disyllables:
khaemo 
sheimo
tomo 
zhaemo
rimo  
 
麻烦你了！

**Comment by alexis-michaud** [comment]
没问题，挺好的！
Yes, it's good that the noun 'mushroom' appears on its own, so it can get the low tone that only monosyllables get in the orthography.
Done in the Toolbox file! bc3dced5c2afd64f6d93bbf319604e694be7cd63
![image](https://user-images.githubusercontent.com/6072524/39414712-63421bf0-4c6d-11e8-941b-3df0c76046e1.png)
