### ISSUE TITLE
Spelling - mostly about -q

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#26]
Hi Alexis,

Could you please add a word final _q_ to the end of ngu ('cry'): nguq.  (Lataddi is not rising, so we're using Ama and Siggeema as a bit of a "standard" here....)

Also, I've been through all the current "AM" orthography words. Could you please amend the following:

- ddiwoq (uphill) - delete the q (cos it has more than one syllable - we did toy with the idea of putting a q on the end of disyllabic L tone nouns, but it wasn't necessary)
- faxi 放心 - change to faexi
- hotaq (red sugar) - delete the q. Also, the English gloss should be 'brown sugar'.
- Kumiq （Kunming）- delete the q
- nguq （CL for waists) - delete the q, cos no q on classifiers
- beijie (Beijing) - capital B
- bitaq (white sugar) - delete the q. I would probably spell this one "beita" - am writing a little paragraph in my paper about the spelling of borrowings. ;-)
- ʂɑ˩tʰɑ˧-dze#˥ (another 'red sugar' which should be 'brown sugar') - spelling is shatazzei (not hotaq!)
- shaehae (Shanghai) - capital S
- xxitoq (behind the house) delete the q

All the rest look great! 

**NB:  I could do these edits for you if/when you give me the go-ahead.**

**Comment by alexis-michaud** [comment]
Done! Many thanks for your patience with my beginner's attempts at Narua orthography.

I will produce an updated PDF after I find the time to input my manuscript notes on the printed copy of the dictionary that I took with me to the field this time.

**Comment by DuMeigui** [comment]
Sounds good, Alexis.  I just downloaded the latest .txt file and these changes to do yet appear.  OK?
R

**Comment by alexis-michaud** [comment]
I did not update the .txt (.lex) file at the time. It should be OK now, following today's (belated) commit (https://github.com/alexis-michaud/na/commit/fcd58bd03f895fa63646001804df1e5b76148a67).
