### ISSUE TITLE
IPA correct?

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#28]
tɕʰɤ˩ʂɯ˩kɤ˩
以前、在过去（汉语借词：‘前时刻’）
IPA: /k/ or /kʰ/?

**Comment by DuMeigui** [comment]
tɕʰɤ˩ʂɯ˩kɤ˩
以前、在过去（汉语借词：‘前时刻’）
IPA:  /k/ or /kʰ/?

**Comment by alexis-michaud** [comment]
Good question! Will try to check this tomorrow (at the farewell lunch with my teacher!)

**Comment by alexis-michaud** [comment]
It _is_ tɕʰɤ˩ʂɯ˩kɤ˩... and there has been a surprise about the meaning! It's 全世界 and not 前时刻. See comment to #29

**Comment by DuMeigui** [comment]
OK, interesting! In that case, based on Ama's pronunciation, the spelling would be amended - I had assumed /kʰ/ - to qiashige.


Borrowings are such a minefield, because there can be a wide divide between how older people pronounce them (lots of mother-tongue interference), and how younger, more educated people (who are the most likely to use the orthography) do.


In the case of the current word, I strongly suspect that younger speakers would say qiashijie. Maybe that would be a safer spelling?


R


________________________________

**Comment by alexis-michaud** [comment]
The spelling of loanwords is an issue, as different people pronounce them differently. Given that users are likely to be mostly below 50 years of age, maybe a transcription based on 'Na-Pu' 纳普 pronunciation would be the most appropriate: something close to the current Southwestern Mandarin pronunciation, with a spelling that follows Narua conventions.

About 'Na-Pu' 纳普:

> [The] variety of Standard Mandarin spoken by Naxi people, and heavily influenced by Naxi pronunciation (...) is locally known as “Naxi Common Speech”: “Na Pu” (纳普) (full form: 纳西普通话 or 纳西族汉语普通话), and is perceived as a substandard variety of Standard Mandarin, this being referred to by contrast as “Biao Pu” 标普, or “Standard Common Speech” (标准普通话). (From [this paper](https://halshs.archives-ouvertes.fr/halshs-01098742).)

I don't know whether people in Yongning use a similar name for the local 'Na-flavoured' variant of Southwestern Mandarin.

**Comment by DuMeigui** [comment]
Yes, I think this is a really good idea, Alexis. I also don't know if the Naq have a saying like "Na Pu", but they certainly have their own way of pronouncing loan words!  ;-)
