### ISSUE TITLE
Words in dictionary with RD for orthography

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#29]
1. ɖʐwæ˧ʝi˥    	放心	to have confidence   	zzhuaeq  yi 	OK    
2. tɕʰɤ˩ʂɯ˩kɤ˩ 	前时刻	in earlier times   	 qiashike? qeshike？[The former spelling signals that it's a borrowing; the latter is more "Na-ified".]
3. te˧˥	代	CLF - generations     	dei	OK
4. tje˩fæ˧  	电饭（锅）	rice cooker  	diafae	OK
5. ʈʂɤ˧fv̩˧  	照顾	to look after   	zhefu OR zhegu?

I can insert these spellings if/when you give me the go-ahead.

**Comment by alexis-michaud** [comment]
"_qiashike_? _qeshike_?" Let's go for the more 'modern-looking' _qiashike_. Speakers can pronounce it in various ways.
"_zhefu_ or _zhegu_?" Typical orthography question; as above, _zhegu_ may be more forward-looking & modern-looking, even though _zhefu_ is definitely closer to the pronunciation of the dictionary's reference speaker (F4).
The changes have been made in commit bdeadf8ab7a0bd97ca94cfe4d67635c393675b52

**Comment by alexis-michaud** [comment]
(I close the issue for now but feel free to re-open it for further discussion.)

**Comment by alexis-michaud** [comment]
Luckily, Dashi happened to be around when I raised the issue and he clarified that it's 全世界 and not 前时刻. Ama confirmed this. 

I'm really bad at Ama's Chinese! In a way it's good that we never talked in Chinese with each other, as it obliged me to leap into 'Narua mode' from the start, but this is a problem for the treatment of Chinese loanwords. They are vastly under-covered in the current version of the dictionary. So much to do...
