### ISSUE TITLE
Inconsistent transcription

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#35]
Item:  ɑ˩pʰo˩, outside
Most example sentences: ɑ˩pʰo˩
However: 
ə˧dɑ˥ | **ə**˩pʰo˩ hɯ˩-ze˥!
**ə**˩pʰo˩-bv̩˥ | lo˧ ʝi˧

**Comment by alexis-michaud** [comment]
Thanks!
There was the same issue in the texts, which had not been fully updated. It's now done.
