### ISSUE TITLE
Another sense

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#37]
ŋwɤ˩ɬi˩mi˩ 
5th month

Another sense of this word is:
Fifth-Month Festival; a festival celebrated by the Na during the fifth month of the lunar calendar, at the same time as the Han Chinese Dragon Boat Festival.

There is an example of a text using the word in this sense in unit 18 of the primer.  ;-)

**Comment by alexis-michaud** [comment]
Done, by commit c99947edd348529298ffe8d6a89125eec38be6ec
Dictionary version incremented to 1.2.2 & new PDF generated for English version: [here](https://github.com/alexis-michaud/na/blob/master/DICTIONARY/NaEnglishChineseDictionary_v1_2_2.pdf).
