### ISSUE TITLE
A tiny tweak

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#39]
ʑi˧˥
to sleep

\xv æ˩ ʑi˧-ze˥
\xe the chicken has gone asleep

Should be: the chicken has gone **to sleep**

**Comment by alexis-michaud** [comment]
OK, done! Tiny it is, but I see the point and I appreciate the progress :-)

I'm reading [a paper written in English](https://arxiv.org/pdf/1807.03341.pdf) that uses 'absent' in a disconcerting way: 

> Too frequently, authors propose many tweaks absent proper ablation studies

> Empirical study aimed at understanding can be illuminating even absent a new algorithm

Here, I'd say 'without', not 'absent'. Interestingly it's a paper about how to make scientific communication clearer and more efficient :-D I can work out the intended meaning, with some effort, but I don't intend to update my own usage and say that I can now propose orthographic representations in Narua absent asking you :-)

To allow future users to access the Narua dictionary's English in the distant future (always assuming that mankind does not ruin the environment beyond repair within centuries), I guess it will need to be re-translated into new forms of English that will have developed in the meantime! Interesting challenge for automatic translation: updating grammatical constructions along a time line. This should be feasible!

**Comment by DuMeigui** [comment]
Ooooh, that is a horrible use of the word "absent".


Speaking of (English) language change, young Kiwi kids have reanalysed "versus" as a verb "verse", hence "verses" (3.SG), and someone can be "versing" someone else. Also yuck!


Have a great weekend,

R


________________________________
