### ISSUE TITLE
Definition of "keeq" - to put into

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#4]
kʰɯ˧˥ ₁ keeq
动词 
⃝1 To put into (e.g. to put into a bag); **to dibble in seeds.** 放，装( 如：装进袋里) ，点种，收下Mettre, mettre dans (ex. : mettre de la farine dans une casserole); libérer, lâcher (ex. : un poulet qu’on tenait par les pattes) ; semer en enfonçant les graines ; ranger, remettre à sa place.

I had to look the word "dibble" up in a dictionary. It's a very unusual word, but I now know what it means. However, I don't think you can say "dibble in (s/thing)".  Also I'm a bit puzzled as to why you would choose to include this one particular definition, but not the English equivalents of libérer, lâcher (ex. : un poulet qu’on tenait par les pattes); ranger, remettre à sa place.  May I suggest you change the \de to: 

**To put into (e.g. to put into a bag); to plant (seeds into soil); to release, to let go (e.g. a chicken held by its legs); to put (something) away.**

**Comment by alexis-michaud** [comment]
This has been gratefully corrected! Thanks
