### ISSUE TITLE
Another small spelling tweak

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#43]
Hi Alexis,

This item:
\lx ‑ho˩
\or ho
\ps suff
\lc ho˩˥

We need to change the orthographic spelling to ho**q**.

Sorry it's taken me so long to notice this!
R :-)

**Comment by alexis-michaud** [comment]
Done!

I don't do any changes on my own because there could be reasons why you choose a spelling other than that expected on the basis of the pronunciation: the IPA transcriptions are single-dialect, whereas the orthography builds on considerations of usefulness in various dialects areas.

**Comment by DuMeigui** [comment]
Yeah, good call. Thanks for trusting me.

R

On 31 Oct 2018 12:06 p.m., Alexis Michaud <notifications@github.com> wrote:

Done!

I don't do any changes on my own because there could be reasons why you choose a spelling other than that expected on the basis of the pronunciation: the IPA transcriptions are single-dialect, whereas the orthography builds on considerations of usefulness in various dialects areas.
