### ISSUE TITLE
Another one

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#44]
\lx qʰwɤ˩α
\sf <nb="B"> 1067
\or khua
\ps adj
\lc qʰwɤ˩˥

Please change spelling to **khuaq**. Thanks!

**Comment by alexis-michaud** [comment]
Change done. So 'intelligent' and 'bad', which are homophonous, are now spelt the same way. This makes great sense to me!

**Comment by DuMeigui** [comment]
Hahaha!

On 31 Oct 2018 12:04 p.m., Alexis Michaud <notifications@github.com> wrote:

Change done. So 'intelligent' and 'bad', which are homophonous, are now spelt the same way. This makes great sense to me!

**Comment by alexis-michaud** [comment]
Just to clarify: pun on the semantics not intended! I just meant literally that it made great sense to me that the orthography and the phonology should coincide here: that two adjectives that are homophonous (also with same underlying representation) should have the same orthographic representation.

**Comment by DuMeigui** [comment]
But also quite funny....

On 31 Oct 2018 16:15, Alexis Michaud <notifications@github.com> wrote:

Just to clarify: pun on the semantics not intended! I just meant literally that it made great sense to me that the orthography and the phonology should coincide here: that two adjectives that are homophonous (also with same underlying representation) should have the same orthographic representation.
