### ISSUE TITLE
Spelling of "tent"

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#48]
Hi Alexis. 

This word: kv̩˧dʑɯ˧˥ (tent).
Previously spelled **gujji**, needs to be changed to **guxxi** please. (It's a dialect thing.)

Thanks!

**Comment by alexis-michaud** [comment]
Done. This change affects

\lx kv̩˧dʑɯ˧˥
\or guxxi

and also affects the following item

\lx õ˧ʈʂwɤ˧-kv̩˧dʑɯ˧˥
\or onzhua guxxi

but it does not affect the following item ('angry, furious'), does it?

\lx gv̩˩dʑɯ˩
\or ggujji

**Comment by DuMeigui** [comment]
Correct. 'Angry, furious' remains ggujji.

**Comment by alexis-michaud** [comment]
OK! That's it, then :-)
