### ISSUE TITLE
dictionnaire (fr + en) : espacement après l'étiquette "(Élicitation)" / A formatting thing in the dictionary: spacing after the mention "(Phonological elicitation)"

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#49]
Every time the phrase "(Phonological elicitation)" occurs, there is no space between the second parenthesis and the next word, e.g. (Phonological elicitation)æ˩gv̩˩ tʰv̩˩-nɑ˥ - there's no space between `)` and `æ`.

**Comment by alexis-michaud** [comment]
Good point! 

Let's add this to the to-do list for an improved stylesheet to produce the PDF.

**Comment by alexis-michaud** [comment]
This issue will be processed together with the various typographical issues for the fresh English & French versions (to be prepared soon-ish: hopefully in 2024). For now the ticket is closed.
