### ISSUE TITLE
Spelling change for an interjection

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#50]
This item:  æ˧-hi˩hi˩
Previously spelled: aexiexie

Having listened to the audio of this text recently, I believe the spelling should be changed to: ehihi. The first morpheme appears to be the same as that of "eyi", as in "eyi keeq". The spelling of the syllable "hi" is a bit of an outlier, but as the word is an interjection, I don't think this is a problem.

This word occurs in the dictionary, and also in the text "Sister's Wedding". (Sorry!)

**Comment by alexis-michaud** [comment]
Thanks!

The spelling _aexiexie_ did sound somewhat disconcerting.

The change is done, but the update to the texts as they appear online, and to the PDF of the dictionary, will take some time, as usual. Don't hesitate to give a nudge in case an up-to-date PDF is needed.
