### ISSUE TITLE
Error in ge and de

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#52]
This entry:
\lx ʈʂæ˧˥
\sf <nb="B"> 170
\sf <nb="2011"> 237
\hm 4
\or zhaeq
\sd <langue="fra"> corps
\sd <langue="eng"> body

\df, \gf, \de, \df are all "articulation". No problem in the French (I presume). For English, though, it needs to be:
**\de (Body) joint. OR Joint (of body).
\ge joint**

**Comment by alexis-michaud** [comment]
Done! 

Many thanks for fixing my deficient English, once more. 👍

**Comment by DuMeigui** [comment]
Your English is almost perfect!

R 🌹

On 26 Jul 2019 22:00, Alexis Michaud <notifications@github.com> wrote:

Done!

Many thanks for fixing my deficient English, once more. 👍
