### ISSUE TITLE
Another spelling mistake - mine this time

### ISSUE THREAD

**Issue by DuMeigui** [alexis-michaud/na#54]
ɻ̍̃˧
<nb="2011"> 350
Current \or:  er
Change to:  eun

**Comment by DuMeigui** [comment]
Whoops, no, not this one - it's already OK. The one that needs to be changed is:
ɲi˩=ɻ̍˥
Current \or:  ni'er
Change to: ni'eun

**Comment by DuMeigui** [comment]
Sorry, Alexis, I was having a brain fart. The original spelling was good all along. (I was misreading diacritics.)

**Comment by alexis-michaud** [comment]
👍
