### ISSUE TITLE
[dictionnaire] préserver La Vague 〜 pour la représentation du mot-vedette dans les exemples : 〜 U+301C WAVE DASH

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#64]
Représentation du mot-vedette dans les exemples : [le remplacement du tiret bas _ par le tilde façon "vague" (〜 U+301C WAVE DASH) dans na.lex](https://github.com/alexis-michaud/na/commit/6ac49cb17099b529a19cbd30edbbab3a08fc4ff3), pour figurer le mot-cible (la vedette), ne suffit pas pour que le PDF contienne ce symbole. Il fait l'objet d'un remplacement par un petit tilde lors du traitement par JLexika.

**Comment by alexis-michaud** [comment]
Résultat dans la version du 3 mai : un petit tilde
![image](https://github.com/alexis-michaud/na/assets/6072524/570e357e-ccb8-4f9a-b971-bb2dacb4cabe)

Visuellement c'est à mon avis trop proche du symbole qui indique la réduplication : par exemple dans /lɑ˩~lɑ˩˥/.

**Comment by alexis-michaud** [comment]
Une autre possilité serait un tiret bien long, avec l'espace qu'il faut avant et après : tiret cadratin U+2014 avec espace avant et après, ou barre horizontale U+2015 (pareil, avec espace avant et après) ?

**Comment by alexis-michaud** [comment]
Pas mieux au 6 juin.
![image](https://github.com/alexis-michaud/na/assets/6072524/085b030d-ca61-4a58-9261-4173c0f3cdd8)
Passage correspondant dans na.lex : 
```
\xv le˧-kʰɯ˧-ze˥
\xe |fg{accomp} 〜 |fg{pfv}
\xn 实施 〜 整体体：甩了
\xf |fg{accomp} 〜 |fg{pfv}
```

**Comment by BenjaminGalliot** [comment]
Je crois que c’est réglé (c’est un vrai cirque en LaTeX, les tildes, vraiment…).

![Copie d'écran_20240618_175711](https://github.com/alexis-michaud/na/assets/23100612/1236a684-4bc6-42fa-a9ed-75f45c44ff9b)

**Comment by alexis-michaud** [comment]
Merci bcp Benjamin ! 
J'ai synchronisé les fichiers et re-généré un PDF. Ca ne marche pas sur ma machine, mais au fond, c'est pas plus mal ainsi : ça remet au centre de l'attention la question des spécifications typographiques que mon installation locale de LaTeX ne sait pas gérer (cf. ticket #80).
![Capture d’écran du 2024-06-19 21-46-35](https://github.com/alexis-michaud/na/assets/6072524/1d01eab3-125d-4a5c-a432-85f81b6ecc98)

**Comment by alexis-michaud** [comment]
Merci bcp Benjamin ! 
Je regarde dès demain (jeudi), en générant à nouveau le PDF.

**Comment by alexis-michaud** [comment]
Ca marche à merveille ! Merci.
![Uploading Capture d’écran du 2024-06-20 16-29-38.png…]()
