### ISSUE TITLE
[dictionnaire] champ \ue non traité : traduction en chinois de la mention "Archaïque"

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#67]
Les mots archaïques sont indiqués au moyen d'un champ \ue :
`\ue archaic`
Il y a 15 exemples dans na.lex.
Pour l'instant, le champ \ue est exclusivement utilisé pour cette étiquette-ci.

La traduction chinoise de "Archaïque" (entre autres termes techniques / liste d'étiquettes), c'est : 古词 ("mot antique"). C'était traité dans la version précédente du dictionnaire (2018). Exemple :
![image](https://github.com/alexis-michaud/na/assets/6072524/3f66c3cd-dccf-4a1c-bfb2-9854670d958b)
Dans la version 2024, le terme "archaic" n'est pas traduit. Il semble que le champ \ue ne soit pas traité (à la différence du champ \xc, par exemple : là, la mention PHONO est bien remplacée par l'équivalent chinois choisi, etc.).
![image](https://github.com/alexis-michaud/na/assets/6072524/e30e04ab-f706-4f32-b081-ceda474732cc)

**Comment by BenjaminGalliot** [comment]
Problème réglé. J’avais laissé la configuration par défaut où un usage était une entité plus complexe, avec un texte descriptif (comme une définition), de potentielles traductions, etc.

J’aimerais cependant savoir s’il peut y avoir plusieurs usages (à lier avec une virgule…), et s’ils peuvent être plus complexes qu’un seul terme à traduire.

![Copie d'écran_20240618_182535](https://github.com/alexis-michaud/na/assets/23100612/1b89aa40-ad6c-450d-9cdc-af6e2b0027f4)
