### ISSUE TITLE
Traitement des mots dont la vedette commence par un tiret

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#71]
Il y a 52 entrées dans na.lex qui commencent par un tiret. Il s'agit de morphèmes grammaticaux.
Pour l'instant, elles n'apparaissent pas dans la version PDF du dictionnaire. 

Exemple : 
```
\lx ‑pʰæ˥di˩
\or paeddi
\ps adv
\ton H.L
\lc pʰæ˧di˩
\sd <langue="fra"> morphosyntaxe
\sd <langue="eng"> morphosyntax

```

Question au passage : y a-t-il déjà, dans le rapport d'exécution de Lexika, une vérification de la correspondance entre le nombre de vedettes (lx) dans le document Toolbox fourni en entrée et le nombre d'entrées dans le dictionnaire produit en sortie ? Si cette fonctionnalité n'existe pas, serait-il justifiable de la faire figurer parmi de futurs développements?

Le risque que des entrées soient ignorées sans que cela ressorte immédiatement est de nature à donner quelques inquiétudes aux autrices & auteurs :)

**Comment by alexis-michaud** [comment]
Dans le XML, l'entrée apparaît bien.

 ```
     <EntréeLexicale identifiant="ⓔ‑pʰæ˥di˩">
        <Lemme>
          <Forme>‑pʰæ˥di˩</Forme>
          <Ton>H.L</Ton>
          <Orthographe>paeddi</Orthographe>
          <FormeDeSurface>pʰæ˧di˩</FormeDeSurface>
        </Lemme>
        <PartieDuDiscours langue="eng">adv</PartieDuDiscours>
```
_etc._

**Comment by alexis-michaud** [comment]
(pas trouvé le temps de regarder dans le rapport de compilation LaTeX quelles traces peuvent se trouver du traitement de ces 52 mots)

**Comment by BenjaminGalliot** [comment]
Ah, ce point est intéressant, je mets cela sur la liste des priorités du na.

Pour la vérification, non, il n’y a pas de message d’erreur spécifique pour le moment car génériquement, tout est vérifiable (entrée lexicale, sous-entrée lexicale, glose, exemple, note, etc., et comme chaque ligne source peut créer dynamiquement de nombreuses entités à la fin, c’est difficile de savoir à l’avance et de manière générale quels éléments seraient à vérifier). Cela dit, pour l’entrée lexicale et `\lx`, je pourrai coder une petite fonction non générique qui comptera le nombre de `\lx` en entrée et le nombre d’environnements `\entrée`. En attendant, une expression rationnelle sur les fichiers lex et tex suffisent. Plus tard, je verrai à intégrer cela dans la configuration, si c’est pertinent (car finalement, la configuration linguistique va créer le XML, or c’est ici la transformation XSL, qui se déroule après et de manière autonome, qui fait sauter quelques entrées…

**Comment by alexis-michaud** [comment]
Traité :100: 
Il semblerait qu'il y ait eu une scorie d'un vieux bricolage du temps des débuts du projet, par lequel un point de code Unicode inhabituel avait été choisi pour le tiret (pour des raisons que j'ai oubliées). 
Un remplacement de ce vieux tiret de derrière les fagots par un tiret tout simple (par [la modif suivante](bb9075d49948c5a670748230eb6f1d0c1ba38402)) a tout débloqué, et les mots dont la vedette commence par un tiret apparaissent tous bien dans le dictionnaire ! 
C'est la fête
