### ISSUE TITLE
[dictionnaire] protéger les tirets bas : ne pas les interpréter en LaTeX comme mise en indice

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#73]
En LaTeX, un tiret bas signale une mise en indice.
Or dans le dictionnaire, le tiret bas est employé dans les gloses (suivant une des "Leipzig Glossing Rules"), pour séparer deux mots d'une expression comportant plusieurs mots mais renvoyant à 1 seul truc. Par exemple: 
`pomme-de-terre`
est une façon de transcrire 3 morphèmes successifs
et
`pomme_de_terre`
transcrit la gloses française d'un morphème unique.

Les exemples dans le dictionnaire, c'est notamment : 
`fut_imm`
pour "futur immédiat"
qui donne : 
![image](https://github.com/alexis-michaud/na/assets/6072524/9257aab9-705d-4f80-a7e3-dcfa798983f0)

alors qu'il faudrait le restituer tel quel: fut_imm

**Comment by BenjaminGalliot** [comment]
Problème réglé !

**Comment by alexis-michaud** [comment]
Merci Benjamin ! 
Quand tu dis "problème réglé", ça veut dire que tu es intervenu sur le moteur Lexika central, et qu'il faut donc que je le mette à jour ? 
Ou tu es intervenu sur un fichier de configuration ? 
Pour rappel, les fichiers de configuration que j'utilise en local, je les mets à jour en ligne dans ce dossier : 
https://github.com/alexis-michaud/na/tree/master/DICTIONARY

**Comment by BenjaminGalliot** [comment]
C'est en local chez moi, mais je pourrais mettre à jour ton fichier ici directement, oui...

**Comment by BenjaminGalliot** [comment]
C’est fait, j’ai modifié le fichier XSL directement ici.

**Comment by alexis-michaud** [comment]
Bien reçu, merci bcp :+1:

**Comment by alexis-michaud** [comment]
C'est bon ! 
![image](https://github.com/alexis-michaud/na/assets/6072524/d7f5413f-da47-43c7-8f17-755b91e40254)
Cet exemple illustre simultanément trois soucis typographiques : le tiret bas (maintenant réglé ! :+1: ), les petites capitales (travail en cours #80), et le symbole pour figurer le mot-cible (#64).
On avance, on avance ! Merci @BenjaminGalliot
