### ISSUE TITLE
encodage des références : champs \rf, \txt, \doi

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#77]
Pour la référence d'un exemple, il y a (au moins) 2 types d'informations : 
- code locutrice/locuteur : F4, F5, M18, M21, M23...
- référence à une phrase d'un texte dans la collection Pangloss. 

La 2e information peut se présenter au moins de 2 façons : 
- le titre du texte et le numéro de phrase, avec comme syntaxe : <identifiant (non informatique) du texte>.<numéro de phrase>. Par exemple : ComingOfAge2.92, Sister.5. (Le numéro avant le point est un "numéro de série" pour les récits racontés plusieurs fois, qui existent donc en plusieurs versions.)
- le DOI de la phrase concernée (qui permet de créer un lien hypertexte vers la phrase dans Pangloss, via le DOI). Par exemple : pangloss-0004589#S92

Ca, ça concerne des exemples qui sont reproduits dans le dictionnaire. Par ailleurs, il serait imaginable d'ajouter le DOI d'exemples choisis qui paraissent intéressants (et donc pertinents à mettre en avant dans le dictionnaire), sans répéter ces exemples dans le dictionnaire pour autant. Il y aurait alors un simple lien. Ca pourrait être un lien hypertexte, avec comme texte affiché l'identifiant "non informatique" (titre + numéro de phrase).

@GuillaumeJacques pourrait s'intéresser à la discussion pour le dico japhug ?

Sans préjuger de l'affichage qui sera fait dans le PDF, comment coder les infos dans na.lex ?
(Pour l'instant c'est tout dans `\rf`, en désordre, et ça fait du bazar dans les tuyaux de Lexika)

Proposition : 
- sous-spécification qd c'est simplement un code locuteur : on indique juste le code. Exemple : 
`\rf F5`
- indication de type pour l'identifiant "pour humains" et le DOI : 
```
\rf <type="texte"> ComingOfAge2.92
\rf <type="DOI"> pangloss-0004589#S92
```
et pour un exemple qu'on souhaite lier depuis le dictionnaire, mais pas répéter dans le dictionnaire : 
\rf <type="DOI" reproduction="no"> pangloss-0004587#S22

@BenjaminGalliot je peux partir sur cette base-là ?

Ca veut dire qu'il y aura 2 champs \rf pour les exemples qui sont repris depuis Pangloss : comme dans l'exemple pris ci-dessus et répété ici : 
```
\rf <type="texte"> ComingOfAge2.92
\rf <type="DOI"> pangloss-0004589#S92
```

Ou te paraît-il préférable d'avoir des champs séparés : \doi pour le DOI, \reftext pour l'identifiant du texte "lisible à l'œil nu" ?

Ou au contraire regrouper les infos faisant référence à un texte dans un seul champ ? (ça serait bien net informatiquement : pas de souci pour apparier des paires de champs \rf)
```
\rf <type="texte" doi="pangloss-0004589#S92"> ComingOfAge2.92
```

**Comment by alexis-michaud** [comment]
Après discussion : 
- `\rf` uniquement pour les codes locuteurs. 
```
\rf M21
\rf F5
```
etc.
- Nouveau champ \txt pour renvoi à un texte. Syntaxe : <identifiant (non informatique) du texte>.<numéro de phrase>. Par exemple : ComingOfAge2.92, Sister.5. (Le numéro avant le point est un "numéro de série" pour les récits racontés plusieurs fois, qui existent donc en plusieurs versions.)
À afficher tel quel.
- Nouveau champ \doi pour le DOI correspondant. `\doi 10.24397/pangloss-0004342#S162`
- Nouveau champ \doisup pour un DOI "supplémentaire", constituant un lien vers un exemple non reproduit dans le dictionnaire. Celui-ci est à discuter : est-ce que c'est une bonne idée. Pas sûr car cela rend le dictionnaire un peu bancal / incomplet: par lui-même, le lien n'est pas "parlant" quand on lit le PDF.

**Comment by alexis-michaud** [comment]
Les liens DOI apparaissent bien, c'est super ! 
Reste à les rendre cliquables. Pour l'instant, ils ne le sont pas.
La syntaxe du lien actionnable est la suivante : 

https://doi.org 
barre oblique 
préfixe qui nous a été assigné 
barre oblique
identifiant du document
dièse
numéro de phrase

Par exemple : 
https://doi.org/10.24397/pangloss-0004539#S6

Le préfixe est : 10.24397

Pour Lexika : il s'agit de concaténer https://doi.org/ et le contenu du champ \doi (ou \doisup).
Par exemple si le champ est : 
\doi 10.24397/pangloss-0004539#S6
il faut créer : 
https://doi.org/10.24397/pangloss-0004539#S6

**Comment by BenjaminGalliot** [comment]
C’est fait.

![Copie d'écran_20240905_205451](https://github.com/user-attachments/assets/d9776abf-657c-41ce-97b4-c675dc196e52)
