### ISSUE TITLE
affichage dans le PDF des entrées lexicales des clitiques, dont la vedette commence par un signe égal =

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#78]
Trois entrées en tout : 
```
\lx =bv̩˧
\lx =ɻæ˩
\lx =ɻ̍˩
```
(actuellement non présents dans le PDF)

Dans le XML, pas de souci, pourtant :
```
      <EntréeLexicale identifiant="ⓔ=bv̩˧">
        <Lemme>
          <Forme>=bv̩˧</Forme>
          <Ton>M</Ton>
          <Orthographe>bbu</Orthographe>
          <FormeDeSurface>bv̩˧</FormeDeSurface>

      <EntréeLexicale identifiant="ⓔ=ɻæ˩">
        <Lemme>
          <Forme>=ɻæ˩</Forme>
          <Ton>L</Ton>
          <Orthographe>lae</Orthographe>
          <FormeDeSurface>ɻæ˩˥</FormeDeSurface>

      <EntréeLexicale identifiant="ⓔ=ɻ̍˩">
        <Lemme>
          <Forme>=ɻ̍˩</Forme>
          <Ton>L</Ton>
          <Orthographe>-er</Orthographe>
          <FormeDeSurface>ɻ̍˩˥</FormeDeSurface>
```

**Comment by alexis-michaud** [comment]
Ca paraîtrait une bonne idée de traiter ce point avant les questions de tri, #70 et #72 : les tests pour le tri seront d'autant plus concluants.

**Comment by alexis-michaud** [comment]
Merci bcp, ça marche ! 
Anecdote au passage : dis donc c'est sensible, ce code ! J'ai mis le signe `=` après les deux autres, et ça marchait pas :
![Capture d’écran du 2024-06-06 09-37-51](https://github.com/alexis-michaud/na/assets/6072524/bec5a88c-446c-44ad-b8eb-0c96346cd669)

En remettant ton code exact (signe égal entre tiret bas et tiret), ça marche !
![image](https://github.com/alexis-michaud/na/assets/6072524/c22dde97-6c45-4c3c-93ac-cf6a2fc23e61)

**Comment by BenjaminGalliot** [comment]
C'est le langage des regex : dans un ensemble, le tiret spécifie une plage, or il n'y a pas de plage possible entre les caractères _ et =.
