### ISSUE TITLE
mise en indice des lettres grecques : généraliser aux divers champs.

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#79]
Le ticket #65 a été traité : mise en indice (sous forme de lettres latines a, b, c...) des lettres grecques dans la représentation du ton d'une entrée, et dans la vedette. 
Il faudrait généraliser ce traitement aux divers champs, dont l'étymologie. Pour l'instant, les lettres grecques y sont restituées telles quelles. Image de la dernière entrée du dictionnaire :
![image](https://github.com/alexis-michaud/na/assets/6072524/c7adc1e1-8432-433b-a829-9e61c4e5154a)

Les lettres grecques dans un passage en langue vernaculaire (soit codé explicitement comme tel, `|fv{}`, soit placé dans un champ qui est défini comme contenant de la langue vernaculaire, comme le champ étymologie, `\et`) sont toutes à mettre en indice en lettres latines.

**Comment by alexis-michaud** [comment]
Un test pour voir si la généralisation est bien en place consistera à vérifier le traitement qui est fait de la note suivante (entrée `\lx ʐo˩α`): 

`\nt <type="tone" langue="fra"> Le comportement tonal du monosyllabe et celui du disyllabe rédupliqué qui lui correspond de façon transparente au plan sémantique ne sont pas en cohérence au plan phonologique. La forme rédupliquée suggère un monosyllabe au ton MH, mais la forme |fv{ɖɯ˧-ʐo˩-ɻ̩˩} (seule acceptable) amène à poser un ton Lα pour le monosyllabe. Or le schéma tonal attendu en réduplication pour le ton Lα est M.H. Le lien entre monosyllabe et disyllabe (forme rédupliquée) paraît donc perdu au plan de la phonologie synchronique.`

La vérification consistera à voir si le α dans "un ton Lα" est bien mis en indice.

**Comment by alexis-michaud** [comment]
Ah,  la virgule chinoise lorsqu’il y a plusieurs étymons consécutifs... c'est de la belle ouvrage ! 

Serait-ce à généraliser aux classificateurs consécutifs ?
![image](https://github.com/alexis-michaud/na/assets/6072524/7da48e7e-9628-43ed-bb86-18bee21c207d)
Visuellement, la mention répétée 【量词】 est plutôt agréable. Mais au plan de la clarté typographique, ça tend à séparer chacun des blocs formés de cette mention et d'un classificateur, ce qui rend moins immédiatement clair, me semble-t-il, le fait qu'il y a plusieurs classificateurs possibles. 
L'information concernant le contexte d'emploi de tel classificateur ou tel autre (le champ `\pdc`) est appelé à être fournie pour un nombre croissant d'entrées (mots) qui ont plusieurs classificateurs possibles. Là aussi, la typographie actuelle ten, me semble-t-il, à séparer un peu beaucoup les blocs. 
![image](https://github.com/alexis-michaud/na/assets/6072524/c91751ca-0788-4e40-a54e-b904d3e62a44)

En bref, je serais plutôt d'avis de factoriser aussi pour les classificateurs. Mais c'est à discuter bien sûr, si tu @BenjaminGalliot as une autre intuition.

**Comment by BenjaminGalliot** [comment]
Oui, ce sera généralisé, c'est ce que je fais d'habitude et pour les classificateurs, on va améliorer ça !

**Comment by BenjaminGalliot** [comment]
Voici le résultat actuel :

![Copie d'écran_20240618_163000](https://github.com/alexis-michaud/na/assets/23100612/e899bec6-a137-44e0-acea-1408942ae4c2)
