### ISSUE TITLE
typographie des gloses : petites capitales

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#80]
Les gloses, |fg{}, sont à composer en petites capitales, conformément aux conventions du domaine. Ici, "nominalisateur", nmlz, à composer en petites capitales NMLZ.
![image](https://github.com/alexis-michaud/na/assets/6072524/d7123010-d24c-4acb-a0a4-08b02a72a858)

**Comment by BenjaminGalliot** [comment]
Elles s’affichent déjà [comme prévu ](https://github.com/alexis-michaud/na/blob/5c90ac837765aa60d59c1b82c4b31a5e13d1a287/DICTIONARY/latex%20alphab%C3%A9tique%20chinois.xsl#L78)en petites capitales chez moi…

**Comment by alexis-michaud** [comment]
Oui, c'est bien traité dans le XML et le .tex. 
Dans le XML (na.xml) :
`<Traduction langue="fra"><style type="fg">nmlz</style></Traduction>`
Dans le `na chinois.tex`, voici ce qui apparaît :
`\stylefg{nmlz}`
Pareil chez toi...?

Pourquoi "mon" PDF n'en tient pas compte ? bizarre bizarre
Un souci de compilation LaTeX, alors ?

**Comment by alexis-michaud** [comment]
(je me permets de rouvrir le ticket du fait que j'aimerais bien parvenir à une solution fonctionnelle chez moi : que je puisse générer le PDF en local)

**Comment by BenjaminGalliot** [comment]
On dirait un problème de fichier manquant... As-tu bien le fichier pour la variante en petites capitales ?

**Comment by alexis-michaud** [comment]
Bonne question ! Oùsqu'y l'est ce fichier ?
C'est dans `latex alphabétique chinois.xsl`, non ?

Je lis : 
`\NewDocumentCommand \stylefg { m } {\textsc{\textcolor{<xsl:value-of select="$couleurpartiedudiscours"/>}{#1}}}
`

Il n'y est pas fait mention de `\textsc`.

Alors que dans le vieux fichier de 2018, y'avait pas la couleur, mais les petites capitales y étaient : 
`\newcommand{\stylefg}[1]{\textsc{#1}}`

M'aurais-tu envoyé une version "soldée" du `latex alphabétique chinois.xsl` ??? Je ne crois pas être allé trifouiller dans cette ligne-là du code. Mais je l'ai peut-être cassé malgré tout ?
Ma version locale est identique (j'ai vérifié) à celle en ligne ici : 
https://github.com/alexis-michaud/na/blob/5c90ac837765aa60d59c1b82c4b31a5e13d1a287/DICTIONARY/latex%20alphab%C3%A9tique%20chinois.xsl#L78

**Comment by alexis-michaud** [comment]
Comment s'organiser ? Si tu fais des améliorations aux fichiers de configuration du na, pourrais-tu me les signaler ? Voire (ça serait le plus simple pour moi) en "pousser" une copie vers la version dans le dossier GitHub où je mets en ligne régulièrement le fichier na.lex ?
DICTIONARY

**Comment by BenjaminGalliot** [comment]
Il y a bien cette commande dans les 2 lignes, regarde bien ! C'est une commande de base de LaTeX (une commande personnelle aurait été en français...). C'est très certainement un fichier manquant, un fichier de police (OTF ou TTF), que tu avais peut-être en 2018 mais pas aujourd'hui. Soit c'est à réinstaller par le gestionnaire de paquets, soit c'est à télécharger manuellement sur la Toile et à placer dans un dossier `.fonts` de ton dossier personnel... Dans tous les cas, ce doit être indiqué précisément dans le fichier de journalisation...

**Comment by alexis-michaud** [comment]
Ah non, c'est na chinois.log, un monstre de 16 Mo ! ouah

**Comment by alexis-michaud** [comment]
ça pourrait être ce bazar-ci ? 

```
luaotfload | aux : font no 25 (nil) does not define feature vert for script latn
 with language dflt
luaotfload | aux : font no 25 (nil) does not define feature vrt2 for script latn
 with language dflt)) (/usr/local/texlive/2024/texmf-dist/tex/latex/ctex/config
/ctex.cfg
File: ctex.cfg 2022/07/14 v2.5.10 Configuration file (CTEX)

```

**Comment by alexis-michaud** [comment]
OK c'est parti ! 
Ah oui, y'a du bazar pour EB Garamond, ça s'est installé comme du chiendent : un vrai cheval de Troie
![image](https://github.com/alexis-michaud/na/assets/6072524/950ea330-673a-4acc-a11b-95d4b9e246eb)
Je vire tout ça ?
(En attendant ta réponse j'installe tes fichiers dans le bon dossier)

**Comment by BenjaminGalliot** [comment]
Ça me paraît assez propre (la documentation, les différents formats…), mais je ne vois pas le contenu pour mieux voir si le problème vient de là. Après, virer tout cela, dur à dire juste comme ça, tu devrais pouvoir désinstaller ça correctement par le gestionnaire de paquets.

**Comment by alexis-michaud** [comment]
Alors déjà j'ai mis les bons fichiers au bon endroit. 
![image](https://github.com/alexis-michaud/na/assets/6072524/09f279b8-3744-4b13-a8c4-14c8afd7ad79)
Au culot, j'essaie de voir si ça règle le problème. Si ça n'a pas marché, je virerai les autres.

**Comment by alexis-michaud** [comment]
Ben non ça a pas suffi.
![image](https://github.com/alexis-michaud/na/assets/6072524/897817b9-0766-4517-a081-fa93dcb1619c)
Et je n'arrive pas à désinstaller
![image](https://github.com/alexis-michaud/na/assets/6072524/21d04819-d9b5-43a7-952e-7b4590be8c2d)
Ah là là ces débutants éternels...

**Comment by alexis-michaud** [comment]
Peut-être juste redémarrer le système, histoire qu'il trouve les fichiers que tu m'as passé ?

**Comment by BenjaminGalliot** [comment]
Le nom du paquet semble être «[ fonts-ebgaramond](
https://packages.ubuntu.com/search?keywords=fonts-ebgaramond) ». D’après ta capture d’écran, les fichiers que tu as sont différents des miens, il y a donc quelque chose à ce niveau-là…

**Comment by alexis-michaud** [comment]
Suppression de fonts-ebgaramond effectuée.
Voici ce qui reste (pourquoi ces fichiers sont encore là, je ne sais pas) : 
![image](https://github.com/alexis-michaud/na/assets/6072524/d451b43d-4fa8-4265-8365-92c51c194578)
![Uploading image.png…]()

**Comment by BenjaminGalliot** [comment]
Alors celles-là sont aussi une EB Garamond, mais une autre… Les 2 sont liées, d’ailleurs, mais informatiquement, on va éviter de s’y perdre. Tu peux donc les effacer.

**Comment by alexis-michaud** [comment]
:+1:
Merci de ton aide, Ubuntu en mode guidé, c'est quand même infiniment plus chouette que tout seul, faut le dire. Je vais passer

**Comment by BenjaminGalliot** [comment]
Après, je ne suis plus sur Ubuntu, donc je ne peux pas totalement simuler…

**Comment by alexis-michaud** [comment]
Ca tourne ça tourne ! J'indiquerai ici le résultat. Pour ce soir je passerai bientôt hors ligne. 
Merci bcp et bon week-end à toi

**Comment by alexis-michaud** [comment]
Bon, ce soir ça a pas marché. Je passe hors ligne (la journée a été longue et il est déjà bientôt minuit ici). 
Je fournirai les résultats ici (après redémarrage de l'ordi, par exemple). Grâce à ton aide je suis sans crainte !
Merci bcp et bon week-end à toi.

**Comment by alexis-michaud** [comment]
Bon, ce soir ça a pas marché. Je passe hors ligne (la journée a été longue et il est déjà bientôt minuit ici).
Je fournirai les résultats ici (après redémarrage de l'ordi, par exemple). Grâce à ton aide je suis sans crainte !
Merci bcp et bon week-end à toi.

**Comment by alexis-michaud** [comment]
Pas mieux ce matin, après redémarrage.
Une recherche de fichiers "EBGaramond" montre que de nouveaux fichiers ont été récupérés hier. 
![image](https://github.com/alexis-michaud/na/assets/6072524/ecd9af8b-8db3-4467-9a93-2cd296bf4c2b)
Est-ce que ça serait TeXLive qui irait chercher les fichiers de la police EBGaramond ailleurs que là où on les lui a préparés ?
Extrait du journal : 
```
luaotfload | cache : Lookup cache loaded from /usr/local/texlive/2024/texmf-var/
luatex-cache/generic/names/luaotfload-lookup-cache.luc.(load cache: extra_ebgara
mond-regular.luc)(load cache: extra_ebgaramond-bolditalic.luc)(load cache: extra
_ebgaramond-bold.luc)(load cache: extra_ebgaramond-italic.luc)
```

**Comment by alexis-michaud** [comment]
Pas mieux ce matin, après redémarrage.
Une recherche de fichiers "EBGaramond" montre que de nouveaux fichiers ont été récupérés hier. 
![image](https://github.com/alexis-michaud/na/assets/6072524/ecd9af8b-8db3-4467-9a93-2cd296bf4c2b)
Est-ce que ça serait TeXLive qui irait chercher les fichiers de la police EBGaramond ailleurs que là où on les lui a préparés ?
Extrait du journal : 
```
luaotfload | cache : Lookup cache loaded from /usr/local/texlive/2024/texmf-var/
luatex-cache/generic/names/luaotfload-lookup-cache.luc.(load cache: extra_ebgara
mond-regular.luc)(load cache: extra_ebgaramond-bolditalic.luc)(load cache: extra
_ebgaramond-bold.luc)(load cache: extra_ebgaramond-italic.luc)
```

**Comment by alexis-michaud** [comment]
Nouvelle tentative : supprimer le EBGaramond qui se trouve ici, dans l'idée que ça amène le compilateur à aller chercher les polices là où on les lui a préparées.
/usr/local/texlive/2024/texmf-dist/fonts/tfm/public
Résultat : pas mieux.
![image](https://github.com/alexis-michaud/na/assets/6072524/2bbacbef-63f8-49c3-ab0f-14d327a7a369)

**Comment by alexis-michaud** [comment]
Question qui concerne mon poste informatique, pas Lexika de façon générale : je ferme le ticket.

**Comment by alexis-michaud** [comment]
Pour info : problème résolu à l'occasion d'une réinstallation complète du système
![image](https://github.com/user-attachments/assets/50796bf6-9005-447a-9345-6094942c663c)
et tout est pour le mieux !
