### ISSUE TITLE
affichage tibétain

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#84]
Il y a quelques formes en naxi, tibétain...
Le logiciel est à ajuster en fonction. En gros, toutes les langues 'exotiques' sont à composer dans la police utilisée pour le na: c'est généralement en Alphabet Phonétique International. 

![image](https://github.com/alexis-michaud/na/assets/6072524/24daa107-959a-4c94-8cb2-6e97f40af0a4)

Le codage ci-dessous est ni fait ni à faire, n'est-ce pas ? J'avais essayé de bricoler en "forçant" une composition typographique façon API, mais Lexika n'est pas du genre à se laisser forcer la main si aisément.
\bw Naxi |fv{/sɑ˥wɤ˧/}

Du coup je repasse à un codage propre
\bw <langue="nxq"> sɑ˥wɤ˧
... mais ça va demander que le code langue soit géré. (À la limite, plein d'autres codes langues aussi : ça serait chouette ! mais mieux vaut sans doute ne pas construire qqch de trop pharaonique)

@BenjaminGalliot Tu me diras !

**Comment by BenjaminGalliot** [comment]
J'ai justement passé toute la semaine sur le tibétain, on pourrait donc même tenter de le mettre aussi plutôt que simplement l'API !

La langue qui s'affiche, c'est directement au niveau du LaTeX, il y a des fonctions pour cela, mais elle sont sensiblement plus difficiles à manipuler, donc je m'en chargerai.

**Comment by alexis-michaud** [comment]
Il y a 2 exemples en naxi (`bw <langue="nxq">`), à afficher en API (même affichage que les passages notés |fv{}). 

Pour le tibétain, encouragé par tes prouesses pour le dictionnaire tibétain, j'ai intégré l'alphabet tibétain pour quelques mots. Par exemple : 
\bw <langue="bod"> rdo rje tshe ring རྡོ་རྗེ་ཚེ་རིང
 Je peux, selon les instructions que tu fourniras : 
- faire un balisage pour les caractères tibétains : par exemple : 
\bw <langue="bod"> rdo rje tshe ring |tib{རྡོ་རྗེ་ཚེ་རིང}
- séparer en 2 champs séparés :
\bw <langue="bod" notation="Wilie> rdo rje tshe ring
\bw <langue="bod" notation="ortho"> རྡོ་རྗེ་ཚེ་རིང
- ou virer l'orthographe, pour pas trop se prendre la tête. Ca paraît dommage quand on est dans l'environnement Lexika, qui encourage à tendre vers la perfection... mais ne t'interdis pas pour autant de le dire quand il te semble que le petit nombre d'exemple rend le travail de développement assez exorbitant pour un enjeu tout petit. Sur le moyen/long terme, Lexika aura besoin de mises à jour, les feuilles de style des dico aussi, et il peut être pas mal d'éviter de multiplier les champs et encodages etc. au-delà du strict nécessaire.

**Comment by alexis-michaud** [comment]
Tant que j'y suis, j'utilise également ce codage `|tib{}` (écriture tibétaine) pour un autre champ, le commentaire sur l'étymologie : `\ec`, et potentiellement aussi pour d'autres champs.

**Comment by alexis-michaud** [comment]
Voilà, j'ai fini d'ajouter l'écriture tibétaine pour les mots pour lesquels elle est connue. Les points d'interrogation indiquent quand il est à peu près sûr que le mot (essentiellement les prénoms) vient du tibétain mais que l'origine exacte n'est pas sûre. 

Juste pour info, quelques commentaires (qui normalement n'appellent pas de particularités de codage) : 

1)
`\bw <langue="bod"> Sgrol ma Bu khrid (/Bu phrug?) |tib{སྒྲོལ་མ་བུ་ཁྲིད/བུ་ཕྲུག?}
`
là c'est une hésitation entre 2 possibilités pour le mot tibétain qui est à l'origine de la 2e moitié du nom : peut-être Bu khrid, peut-être Bu phrug

2)
`
\bw <langue="bod"> ? |tib{?}`
là c'est qu'il n'y a pas du tout d'hypothèse pour l'instant.

3) 
```
\lx no˧no˧-ɖɯ˩mɑ˩
\or Nono Ddeema
\bw <langue="bod"> ? + Sgrol ma |tib{? + སྒྲོལ་མ}

```
là c'est un prénom composé pour lequel on ne sait pas du tout à quoi correspond en tibétain la première partie ("Nono").

**Comment by BenjaminGalliot** [comment]
La prise en charge du script tibétain a été ajoutée.

![Uploading Copie d'écran_20240909_182540.png…]()

Comme on en avait parlé je ne sais plus où, il faudra penser à améliorer certaines balises et métadonnées pour bien différencier dans l’absolu les données des métadonnées de langue. Cela fera partie des finitions.
