### ISSUE TITLE
Afficher l'étymologie (en na) de mots d'emprunt

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#85]
@BenjaminGalliot Le travail sur le dictionnaire progresse peu à peu. Globalement la structure reste simple, et les ambitions en termes de formalisation informatique de la _structure du lexique_ modestes. 

Voici néanmoins que surgit une question qui sort de l'ordinaire et pourrait titiller ton goût des défis.

L'entrée "opium" constitue un mot d'emprunt : elle vient du chinois 鸦片. Mais celui-ci est assorti, en na, d'un mot qui désigne le tabac, et qui facilite l'acclimatation d'un mot qui n'existait pas auparavant. C'est du "tabac-opium".

Voici (un peu élagué pour le propos de l'exposé) le début de l'entrée, qui comporte trois informations : 
- le champ `\bw` signale qu'il s'agit d'un emprunt
- les champs `\et` fournissent l'identité des deux éléments dont le mot est composé
- les champs `\ec` fournissent un p'tit commentaire érudit (qui vaut ce qu'il vaut), en français et en anglais et en chinois.
```
\lx jɤ˧pʰi˧-jɤ#˥
\bw <langue="cmn"> 鸦片
\et |fn{鸦片}
\et jɤ˧3
\ec <langue="fra"> L'opium se fume, comme le tabac. En moso, il a été emprunté comme ‘tabac-opium'. Le mot pour ‘tabac', /|fv{jɤ˧3}/, pourrait également être un emprunt au chinois, mais d'une date bien antérieure. Lorsque le mot ‘opium' a été emprunté, le mot ‘tabac' était pleinement acclimaté (à supposer qu'il s'agisse bien d'un emprunt) et pouvait servir à guider l'interprétation du nouveau mot emprunté, ‘opium'.
\ec <langue="eng"> Opium is smoked, like tobacco. In Na, it was borrowed as ‘opium tobacco'. The word for ‘tobacco', /|fv{jɤ˧3}/, might be an early borrowing from Chinese, too, but by the time the word ‘opium' was borrowed, the word ‘tobacco' was well-integrated (supposing that it was originally a loanword) and could assist in guiding the interpretation of the new loanword, ‘opium'.
\ec <langue="cmn"> 鸦片像烟草一样被吸食。在摩梭中，它被借为‘鸦片烟’。‘烟’/|fv{jɤ˧3}/可能也是从汉语中借用的词，但借用时间估计是更早。当‘鸦片’一词被借用时，估计‘烟’已经完全融化到摩梭适词汇中（假设它确实原来是汉语借词），可以用来帮助解释新借用词‘鸦片’的含义。
```

Pour l'instant, le PDF ne porte pas l'info étymologique, seulement l'info liée au statut de mot d'emprunt. 
![image](https://github.com/alexis-michaud/na/assets/6072524/6458dfef-6960-4b6f-a437-fd02c97ce274)

Serait-il souhaitable de tout afficher ? L'info relative au statut de mot d'emprunt (comme actuellement), et aussi l'info relative à l'étymologie, comme si le mot n'était pas un emprunt.

Ou est-il souhaitable (comme le suggère le traitement actuel de cette entrée par Lexika, tel que je le comprends/constate) de réserver un traitement séparé aux mots d'emprunt, l'origine du mot en langue étrangère constituant une info de même niveau que l'étymologie pour les mots non codés comme des emprunts ?

(si c'est pas clair on en parlera de vive voix à l'occasion)

**Comment by BenjaminGalliot** [comment]
On peut évidemment tout afficher… Le [yuanga](https://gitlab.com/BenjaminGalliot/Lexika/-/blob/ma%C3%AEtresse/exemples/yuanga/yuanga.lex) a d’ailleurs beaucoup d’informations pour l’étymologie… En revanche, je crois comprendre que tu utilises 2 balises `\et`, une pour chaque élément de même niveau « chronologique », et non pas, comme plus habituellement, des étymons successifs… Si les deux cas peuvent se présenter au sein de ton dictionnaire, il faudra trouver un moyen de les discriminer. Le [japhug](https://gitlab.com/BenjaminGalliot/Lexika/-/blob/ma%C3%AEtresse/exemples/japhug/japhug.lex) avait un cas que je trouve similaire (avec des `\lf Component 1` et `\lf Component 2`).

**Comment by alexis-michaud** [comment]
OK alors plutôt que de se lancer tête baissée dans une distinction entre `\lf` pour la fonction lexicale (étiquette) et `\lv` pour la forme, on part sur un champ "étymon synchronique", "prov" ? ("pr" ?)
Au lieu de : 
\et mi˩ɬi˩
\et ʁo˧bv̩˧

on passe à : 
\ets mi˩ɬi˩
\ets ʁo˧bv̩˧

Ainsi l'espace est ouvert pour distinguer une "vraie" étymologie d'un lien synchronique de type "origine/étymologie/provenance".

**Comment by alexis-michaud** [comment]
Changement effectué dans na.lex : passage à 
`\ets`
(qui pointe vers une autre entrée du dictionnaire).
Ce qui ouvre un espace pour fournir en étymologie de vraies étymologies (avec une profondeur diachronique), c'est super.
