### ISSUE TITLE
Classement des entrées : une curiosité pour la lettre H

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#86]
Rigolo : ça commence par les /ṽ̩/, avant la première voyelle habituelle, /ɑ/.
![image](https://github.com/alexis-michaud/na/assets/6072524/91262e3f-2fd9-4dc2-9c50-d17f88d20033)
Pourtant, le fichier de configuration dans sa version actuelle ne traite pas séparément la syllabe /hṽ̩/.
```
    ordre lexicographique:
      graphèmes: [ɑ, ɑ̃, æ, æ̃, b, ɕ, d, dz, dʑ, ɖ, ɖʐ, e, ɤ, ə, f, g, ɣ, h, i, ĩ, j, ʝ, k, kʰ, l, ɭ, ɬ, m, n, ɳ, ɲ, ŋ, o, õ, p, pʰ, q, qʰ, ɻ, ɻ̩, ɻ̩̃, ʁ, s, ʂ, t, tʰ, ts, tsʰ, tɕ, tɕʰ, ʈ, ʈʰ, ʈʂ, ʈʂʰ, u, ɯ, v̩, [ṽ̩, ṽ̩], w, w̃, z, ʑ, ʐ]

```
Pour les autres lettres, l'ordre est celui attendu, semble-t-il (j'ai regardé pour G, pas pour toutes les lettres).

**Comment by alexis-michaud** [comment]
Peut-être à rapprocher de #70 ? (autre question de classement)

**Comment by BenjaminGalliot** [comment]
Une vérification rapide avec le test du trieur m’a donné ces résultats :

```julia
OrderedCollections.OrderedDict{String, Vector{Any}} with 2 entries:
  "hṽ̩˩α"    => [Any[(18,)], Any[(0, 8)], Any[(0,)]]
  "hɑ˧ɭɯ#˥" => [Any[(18, 1, 26, 56)], Any[(0, 0, 4, 0, 0, 1)], Any[(0, 0, 0, 0)]]
```

On remarque que pour « hṽ̩˩α », le second graphème ne semble pas exister… Donc en regardant les graphèmes de l’ordre lexicagraphique, décomposés, puis le graphème du mot trié, on remarque cela :

```julia
julia> "[ṽ̩, ṽ̩]" |> collect
9-element Vector{Char}:
 '[': ASCII/Unicode U+005B (category Ps: Punctuation, open)
 'ṽ': Unicode U+1E7D (category Ll: Letter, lowercase)
 '̩': Unicode U+0329 (category Mn: Mark, nonspacing)
 ',': ASCII/Unicode U+002C (category Po: Punctuation, other)
 ' ': ASCII/Unicode U+0020 (category Zs: Separator, space)
 'v': ASCII/Unicode U+0076 (category Ll: Letter, lowercase)
 '̩': Unicode U+0329 (category Mn: Mark, nonspacing)
 '̃': Unicode U+0303 (category Mn: Mark, nonspacing)
 ']': ASCII/Unicode U+005D (category Pe: Punctuation, close)

julia> "ṽ̩" |> collect
3-element Vector{Char}:
 'v': ASCII/Unicode U+0076 (category Ll: Letter, lowercase)
 '̃': Unicode U+0303 (category Mn: Mark, nonspacing)
 '̩': Unicode U+0329 (category Mn: Mark, nonspacing)
```

On voit bien que ce graphème n’est pas composé de la même manière : dans l’ordre du fichier de configuration, c’est soit `ṽ` suivi de la ligne verticale souscrite, soit `v` suivi de la ligne souscrite puis du tilde, alors que dans le mot testé, c’est `v` suivi du macron puis de la ligne souscrite… Comme ce dernier graphème n’est pas dans la liste, il n’a tout simplement pas été traité (il a été considéré comme invisible au regard du tri).

Idéalement, je pourrais ajouter un avertissement supplémentaire dans un cas comme celui-ci, mais il faudra affiner, car finalement, c’est une simple combinaison de caractères (dont des combinants) non configurée, mais les caractères pris séparément pourraient l’être…

**Comment by alexis-michaud** [comment]
Ah, chapeau, c'est super cette mise à plat de caractères dont le rendu dans la liste est identique.

Du coup la rustine pour régler le problème, ça va être d'ajouter v suivi du tilde puis de la ligne souscrite. 

A y est c'est fait... et ça marche !
![image](https://github.com/alexis-michaud/na/assets/6072524/043394e6-6f81-4be9-b021-6d4c423fde73)

(Je pensais que c'était ça, le premier des deux ṽ̩ de la liste : v suivi du tilde puis de la ligne souscrite. Le ṽ suivi de la ligne verticale souscrite devrait pouvoir être retiré de la liste, sans inconvénient. Le logiciel que j'utilise, Kate, ne parvient pas à le trouver dans na.lex. Ce qui n'est pas surprenant, car il ne correspond pas à une combinaison que puisse produire mon clavier de saisie, qui n'utilise pas de caractère 'v avec tilde' "mono-code". Enfin c'est peut-être pas mal de le laisser à tout hasard?)

À titɻe pɻéventif, j'ai fait pareil pour le ɻ̩̃, qui peut pareillement être composé dans 2 ordres différents.
`[ɻ̩̃, ɻ̩̃]`
