### ISSUE TITLE
Commentaires et notes : ticket mis à jour

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#87]
Fermeture du ticket #83 et nouveau point des tâches à réaliser : types de notes : les nouvelles étiquettes : 
- `"comp"` : gestion des _comparanda_ dans d'autres langues : mots apparentés (ou du moins, termes de comparaison pour un travail historique).
Pour l'instant les rares exemples sont au format suivant
`\nt <langue="naxi" dom="comp"> ʈʂə˞˩`
Il y a aussi des termes de comparaison en langue pumi ; ceux-là ne sont pas à afficher dans le PDF, comme l'indique l'étiquette `print="n"`
`\nt <langue="pumi" dom="comp" print="n"> bæ51`
mais malgré tout ça serait bien que le codage en XML soit conforme à la logique Lexika et ne fasse pas de bazar dans les tuyaux. Il semble par exemple que \nt soit défini de base comme étant du français, ce qui serait à modifier 
![image](https://github.com/alexis-michaud/na/assets/6072524/0b439383-b46f-4b12-9409-5a27c2e3da36)
- `"dialect"`:
`\nt <dom="dialect" langue="fra"> Roselle Dobbs fournit l'indication selon laquelle ce nom de lieu se prononce /|fv{w̃æ.bi}/ dans le village d'Aggowua |fn{阿古瓦}, au nord d'Alawua.`
- champ `\np`, notes phonético-phonologiques (phon* dirait Guillaume Wisniewski, qui lit: "phon- étoile")
`\np <langue="fra">`
Par exemple : 
`\np <langue="fra" dom="ton"> Parmi les classificateurs de catégorie tonale Lβ, certains donnent plus volontiers un schéma tonal MH# lorsqu'ils sont associés à un démonstratif, tandis que d'autres donnent plus volontiers un schéma H#. Dans l'état actuel de la langue, il paraît s'agir d'une préférence parmi des variantes toutes deux acceptables. Pour ce mot-ci, le schéma préféré est MH#.
`
Il est envisageable de tout transformer en note, \nt, si ça simplifie la structure. 
`\nt <langue="fra" dom="ton">`
Au fond ça serait plus cohérent d'utiliser \nt et des étiquettes, non ? Plutôt que d'avoir un champ séparé pour les notes phonético-phonologiques, alors que les autres notes sont des `\nt` pourvues d'une étiquette.
(Pertinent pour le dictionnaire anglais et français, et aussi pour le dictionnaire chinois, dans la philosophie actuelle qui consiste à y inclure à peu près tout. Philosophie dont il serait opportun de discuter ensemble à un moment, et on la fixerait par écrit dans l'intro.)
- commentaires au sujet des variantes : 
histoire d'avoir un exemple sous la main, j'ai traduit en 3 langues un commentaire au sujet d'une variante. C'est pour le mot "opium"*. 
```
\va <speaker="M23"> ʈʂʰæ˧v̩˧-nɑ˥
\vf Sens de l'expression: “médicament noir"
\ve This noun phrase means ‘black medicine’.
\vn 这个名词的意思是‘黑药’。
```
Pour l'affichage : en suivant la philosophie proposée (ouverte à discussion) : dans le dico chinois les 3 y seraient ; dans l'anglais, y'aurait juste l'anglais ; dans le français, juste le français.

Pour l'encodage : pas d'obstacle à réencoder en mettant la langue comme attribut, et en uniformisant la balise-champ, pour ne pas multiplier les champs; ça pourrait donner 'vc', 'c' pour 'commentaire' comme dans 'xc', et 'v' pour variante, comme dans 'va'. Dans l'attente de tes instructions.

*j'espère qu'avec ce mot je vais pas attirer les foudres de la Censure sur notre projet : entre les substances récréatives illicites, les mots tabous [les lexicographes ne respectent pas la pudeur], et les indications géographiques jalousement protégées / langues & peuples tabous, il pourrait bien y avoir dans `na.lex` de quoi faire réagir la plupart des filtres de surveillance de masse d'ici et d'ailleurs...

en cas d'absence d'étiquette de langue, il faut faire l'hypothèse selon laquelle l'information est pertinente pour les 3 versions linguistiques, et est à répéter pour chacune des langues. L'absence d'étiquette langue serait une sorte de factorisation par laquelle l'information en question cumule toutes les étiquettes langue possibles (pour ce qui concerne les "méta-langues", celles dans lesquelles le dictionnaire est publié : fra+eng+cmn).

Par exemple ci-dessous :

```
\xv ə˧bo˧-tɕi˥
\xe paternal uncle, father's younger brother
\xn 叔叔：父亲的弟弟
\xf oncle paternel cadet du père
\xc <dom="ton"> H#
```
L'information selon laquelle l'expression porte un ton H# n'est pas "en français" plus qu'en anglais ou en chinois, et elle concerne toutes les langues. Elle serait à composer typographiquement selon la langue concernée, d'après l'indication fournie par l'étiquette "domaine linguistique" (ici : "`ton`").

De même pour la note sémantique (commentaire d'exemple) ci-dessous :
`\xc <dom="synt"> |fg{clf}: |fv{/ɖɯ˧-ɭɯ˧/}
`
Il faudra que je te fournisse une liste de traductions pour les divers types de commentaires.

**Comment by alexis-michaud** [comment]
Pour les notes, pour bien distinguer le domaine linguistique concerné (sémantique, syntaxe, phonologie, dialectologie...) du type de note (est-ce que c'est de l'historique qui n'intéresse pas la majorité des lecteurs, ou des infos complémentaires fournies en bon ordre), l'attribut "type" a été modifié comme suit : 
- l'attribut "type" est désormais réservé à un méta-commentaire : est-ce que c'est de l'historique (type="hist"), ou non (pour l'instant, pas d'autres types que "hist")
- un attribut "dom", pour "domaine", est utilisé pour : sem (sémantique), synt (syntaxe), dialect (dialectologie), phono (phonologie), ton (tonologie). 

Pour la composition typographique, la traduction de ces étiquettes dans les 3 langues pourrait être comme suit : 
sem：Sémantique Semantics 语义
synt：Syntaxe Syntax　句法
morpho：Morphologie Morphology　形态
phono：Phonologie Phonology 音系学
tone：Tonologie Tonology 声调
dialect：Dialectologie Dialectology 方言学

Les commentaires fournis dans les 3 langues ont vocation à être de simples traductions: à terme, toutes les infos (généralement rédigées à l'origine en français) seront traduites dans les 3 langues, de sorte qu'en principe il ne sera pas nécessaire d'avoir les commentaires dans les 3 langues. Pour faire les choses proprement, comme on aime, il y a un choix à faire parmi les infos. 
Pour la version française, je proposerais de ne rien inclure en anglais (je compte sur ta francophonophilie militante pour pencher dans le même sens), qui même avec une couleur différente tend à ne pas être hyper-discret en comparaison du français. Ni définitions, ni traductions, ni traductions d'exemples, ni commentaires. 
Pour la version anglaises, je proposerais d'inclure les définitions en français, les traductions d'exemples en français, mais pas les commentaires en français. À discuter (aussi avec des utilisatrices / utilisateurs de la version anglaise). Au stade actuel, où les traductions anglaises sont un peu inégales, la présence du français (globalement pas trop dur à déchiffrer pour les anglophones) rend des services pour aider à corriger l'anglais.

**Comment by alexis-michaud** [comment]
Pour la mise en page, en regardant les commentaires qui s'affichent désormais (merci pour ce progrès !), deux remarques.
1) Pour l'affichage des notes dans le PDF, comme elles ne se détachent pas beaucoup par rapport au reste du texte (par exemple quand elles suivent une traduction d'exemple), est-ce que ça ne serait pas indiqué de signaler leur statut de note par une 'étiquette' dans le PDF ?
Par exemple ici :
[image.png](https://lacito.zulipchat.com/user_uploads/35580/v5IKsNQh53r1ou4LZArnEHFo/image.png)
(deuxième entrée du dictionnaire)
Une mention 'note' pourrait être ajoutée avant le type de note :
oie et jars (tonologie : LM+#H-)
deviendrait
oie et jars (note : tonologie : LM+#H-)
Si le mot "note" est bcp répété, ça n'est pas bien grave. Une bonne démarcation est utile pour que les utilisatrices et utilisateurs puissent commodément prendre connaissance des infos, c'est ça le but.
En anglais, ça serait pareil : "note". En chinois : “注：”

Pour les éventuelles notes sans étiquette / attribut de type dom, le traitement serait le même : utilisation d'une mention "note :".

Faut-il deux points ou un tiret après la mention "note", pour ça, je n'ai pas d'intuition forte. Un tiret (plus long que le simple trait d'union - ) pourrait aller :
oie et jars (note -- tonologie : LM+#H-)

Si l'idée d'ajouter le mot "note" ne te paraissait pas bonne, une autre possibilité consisterait à mettre en gras le type de note :
oie et jars (tonologie : LM+#H-)

2) Quand une note ne comporte pas d'info "langue" (étiquette lang="..."), elle est à afficher dans les langues du dictionnaire : chinois, anglais et français pour la version chinoise du dictionnaire, français et chinois pour la version française, anglais, chinois et français pour la version anglaise.

Pour cet exemple, la version du dico étant le chinois, il y aurait 1 affichage en chinois (et en anglais) à faire, pas juste le français comme à présent. Ainsi ça sera bien en cohérence avec la langue du dictionnaire.
公鹅与母鹅（注：声调：LM+#H-） • goose and gander (note: tonology: LM+#H-) • oie et jars (tonologie : LM+#H-)

**Comment by alexis-michaud** [comment]
Composition des exemples et de leurs notes : 
au lieu de
- transcription
- toutes les traductions
- tous les commentaires
une organisation par blocs serait plus lisible : après la transcription, fournir
- traduction + commentaires en chinois
- traduction + commentaires en anglais
- traduction + commentaires en français

**Comment by BenjaminGalliot** [comment]
C’est fait. J’ai ajouté un petit symbole pour marquer le début d’une note (d’exemple ou d’une autre entité), et mis le type/domaine de note entre parenthèses juste avant. La note d’une entité parente générale reste multilingue, et la note non liée à une langue à la fin d’un exemple (typiquement une information tonologique) reste à la fin des 3 blocs linguistiques. 
On pourrait aussi varier les symboles…

![Copie d'écran_20240905_214523](https://github.com/user-attachments/assets/a1bfb5cd-8b58-46e5-8cec-091c2949f038)
![Copie d'écran_20240905_214609](https://github.com/user-attachments/assets/ce92579e-4610-47e0-b6b6-2d6e6b20fb7d)

**Comment by alexis-michaud** [comment]
De même que ce ticket avait été rédigé après la fermeture du ticket #83, pour bien mettre à jour les besoins en fonction de l'avancement du travail, de même ce ticket peut maintenant être fermé et les demandes restantes transférées vers un nouveau ticket. La conversation continue donc ailleurs (ça avance, merci !!!)
