### ISSUE TITLE
dictionnaire : compteur d'entrées

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#89]
J'ai un souvenir selon lequel le dictionnaire japhug avait un compteur d'entrées ? qui permettait d'indiquer, en intro, le nombre d'entrées "au jour J". Classe! 
Est-il envisageable de généraliser cette fonction (si celle existe) et fournir l'info pour le na? Il s'agirait de compter le nombre de `lx` dans `na.lex`, qui fournit le nombre d'entrées. (Aujourd'hui : 3 142 !)
![image](https://github.com/user-attachments/assets/8ea1fdf3-14d0-42e1-92fe-6a9167844ccd)

Cela permettrait d'indiquer en introduction ce chiffre. 

Pour l'intro anglaise: "Systematic elicitation of large amounts of vocabulary was not carried out, hence the limited number of entries: on the order of 3,000 (the current count stands at yyyy)."

**Comment by BenjaminGalliot** [comment]
C’est assez simple, oui, mais je ne parlerais pas de généralisation, puisque chaque auteur peut désirer ce qu’il veut (compteur d’entrées brutes, ou ventilées par les parties du discours, etc.). C’est une bête ligne dans le XSL !

**Comment by alexis-michaud** [comment]
Les endroits où indiquer les chiffres sont signalés dans l'introduction (dans ses 3 déclinaisons : cmn, fra, eng) par un "`xyz`". (Le nombre d'occurrences est le même dans les 3 langues : dix-sept.)

**Comment by BenjaminGalliot** [comment]
C’est fait, j’ai ajouté les commandes dans la version chinoise (tu pourras les ajouter quand tu voudras dans les 2 autres version). La commande est `\obtenircompteur{[PDD|total]}`.
