### ISSUE TITLE
dico na : un lien "synonyme" qui ne fonctionne pas bien : la faute au tilde ?

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#91]
C'est dans l'entrée dzo˧˥ /dzo˧˥/ zzoq 'Toucher, tripoter'.

![image](https://github.com/user-attachments/assets/95b6e084-ca98-4ebc-a128-fc579c3d459e)

Le lien va vers la page 358 (la table des matières) au lieu de pointer vers l'entrée en question (page 325).
Référence : version du 4 septembre, produite sur ton ordinateur (@BenjaminGalliot).

Pourtant les autres liens vers des synonymes marchent.

Ｐiste probable : la faute au tilde ? 
En effet, le second lien "synonyme" dont le texte contient un tilde présente le même bogue. 

Il s'agit de : 
tɑ˧ho˧  'Ensemble'.
(...)
【同义词】ʈʂwæ˩~ʈʂwæ˧˥

Les tildes : clairement un enfer dans LaTeX, disais-tu, et ça se vérifie.
"À l'impossible nul n'est tenu" : s'il y a quelques liens comme ceux-ci qui ne marchent pas, bon, c'est pas la fin du monde.

**Comment by BenjaminGalliot** [comment]
C’est corrigé. J’avais remarqué ce problème qui ne m’avait pas fait beaucoup rire il y a plusieurs semaines avec `#`, mais  sur le coup, je n’avais pas songé que `~` (fou que j’étais) était aussi concerné.
