### ISSUE TITLE
affichage des termes de comparaison pour la linguistique historique : cognats et comparanda

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#94]
à faire par le 1er auteur du dico : gestion des `"comp"` : les _comparanda_ dans d'autres langues : mots apparentés (ou du moins, termes de comparaison pour un travail historique).

Pour l'instant les rares exemples sont au format suivant
`\nt <langue="naxi" dom="comp"> ʈʂə˞˩`
Il y a aussi des termes de comparaison en langue pumi ; ceux-là ne sont pas à afficher dans le PDF, comme l'indique l'étiquette `print="n"`
`\nt <langue="pumi" dom="comp" print="n"> bæ51`

C'est important que le codage en XML soit conforme à la logique Lexika et ne fasse pas de bazar dans les tuyaux ; et pour cela, que le codage dans na.lex soit amélioré, avec des balises spécifiques, telles que cog pour les cognats et comp pour les comparanda.

**Comment by alexis-michaud** [comment]
premier exemple traité : 
`\nt <dom="comp" langue="nxq"> cognat du naxi /kʰwɑ˩/
`
réencodé comme : 
`\cog <langue="nxq"> kʰwɑ˩`
en employant `\cog` pour les cognats.

**Comment by alexis-michaud** [comment]
Voici les infos pour affichage trilingue, dans l'ordre "français-anglais-chinois" des traductions : 
langue=
- "nxq" : 
naxi
Naxi
纳西语

- "lata1234" : 
na de Lataddi
Lataddi Narua
拉塔地摩梭话

- "pmi" : 
pumi
Pumi
普米语

**Comment by alexis-michaud** [comment]
Du coup la balle passe dans ton camp ?

**Comment by BenjaminGalliot** [comment]
C’est fait, j’ai ajouté cela à la fin de l’entrée. Tu me diras s’il y a une couleur particulière à mettre…

![Copie d'écran_20240910_170512](https://github.com/user-attachments/assets/c34b9528-04a8-4404-afd6-94da30e507bc)

Tu feras attention, il y a le comparandum « ʈʂʰæ35 » (pumi) qui n’est pas invisible, je ne sais pas si c’est voulu…

**Comment by alexis-michaud** [comment]
petite régression lors de la création du bloc "comparatisme"

**Comment by alexis-michaud** [comment]
Identifiée le 2 octobre. Correction en cours

**Comment by alexis-michaud** [comment]
Corrigé ! merci @BenjaminGalliot
