### ISSUE TITLE
dictionnaire na : déplacer les commentaires après les définitions

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#95]
L'affichage des commentaires a bcp progressé, c'est super ! 
Les commentaires sont assez fournis, et trilingues (pour la version chinoise), de sorte qu'ils prennent pas mal de place. Afin d'éviter de trop éloigner la définition du mot du début de l'entrée, il serait souhaitable de déplacer les commentaires après les définitions, non ?
Un exemple assez extrême (toute la colonne est occupée par un commentaire, dans les 3 langues) :
![image](https://github.com/user-attachments/assets/ddcc7404-f839-4870-a6a7-02fc5081e56a)

Un autre exemple, pour lequel le pire est à venir : quand je prendrai le temps de traduire la note en anglais et en chinois, ça va rudement éloigner la définition du début de l'entrée.
![image](https://github.com/user-attachments/assets/fca7eec8-610d-42a0-9042-33ef5a283831)

(Cela tient au style un peu bavard, "dilué", des notes de ce dictionnaire, qui expliquent des choses pas toujours absolument centrales. Mettre les choses bien à plat, ça prend de l'espace.)

Merci bcp !

**Comment by alexis-michaud** [comment]
Tant qu'on y est ça serait génial aussi de générer un **ordre des notes** spécifique à la version linguistique du dictionnaire : 
- chinois : le chinois d'abord, puis l'anglais, le français à la fin
- français : le français d'abord, le chinois ensuite (pas d'anglais)
- anglais : l'anglais d'abord, le chinois ensuite, et enfin le français

Merci bcp !

**Comment by BenjaminGalliot** [comment]
C’est bon.

![Copie d'écran_20240909_182854](https://github.com/user-attachments/assets/902a58dc-52b7-4fd8-835a-614cbeae71b5)

Sinon, j’ai préparé le terrain dans le XSL pour que l’ordre des langues soit variable selon la langue principale du dictionnaire.
