### ISSUE TITLE
parenthèse fermante après liste de variantes (\va), lorsqu'une note se rapporte à ces variantes

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#96]
Lorsque la liste de variantes achève la première ligne d'une entrée lexicale, une parenthèse fermante est bien présente, comme il se doit. Cela, que l'information consiste simplement en une confirmation de la prononciation de la locutrice principale & co-autrice, comme ici : 
![image](https://github.com/user-attachments/assets/5eefa020-8efc-4570-80b4-9c827421cf38)
ou que l'information comprenne un champ en langue vernaculaire indiquant une autre forme, comme ci-dessous.
![image](https://github.com/user-attachments/assets/bded2091-9307-4330-a880-af902152ad98)

En revanche, lorsque la liste de variantes est suivie d'un commentaire (/note) qui s'y rattache (et appartient donc au même bloc Lexika), la parenthèse qui contient la liste des variantes n'est pas refermée. La mise en page enchaîne directement, en passant à la note, et la parenthèse n'est pas refermée.
![image](https://github.com/user-attachments/assets/37531388-86d5-421e-ac9c-2d4d52353bbd)

Le correctif à apporter consisterait donc à refermer la parenthèse avant le ou les commentaires (/notes) : ici, juste après la forme `ɲi˧mi˧ dʑɯ˩ ʈʰɯ˩`. 
Ce qui n'est sans doute pas de la tarte au plan de la mise en œuvre informatique : c'est une nécessité typographique (ne pas refermer la parenthèse 3 km plus loin, après toutes les notes, qui peuvent potentiellement occuper plein de lignes successives), tandis qu'au plan sémantique, il y a continuité puisqu'on reste au sein du bloc "variantes".

**Comment by BenjaminGalliot** [comment]
Comme je trouvais cette anomalie très étrange au vu de la structure du XSL, je suis allé vérifier ce que je supposais : la parenthèse se referme bien, mais après l’ensemble des notes de ce bloc, donc potentiellement très loin si les notes sont multilingues… On voit bien ici que c’est une note multilingue de la deuxième variante sur les trois.

![Copie d'écran_20240921_003357](https://github.com/user-attachments/assets/23e570b8-a025-4f6a-9a86-c33f498d1088)

**Comment by alexis-michaud** [comment]
Ah oui, bien vu ! Au temps pour moi. Oui oui, la parenthèse qui se referme après 10 lignes de note, pas évident.

La version française sera mieux pour ça, étant délestée de toutes les infos en anglais, et (si je me souviens bien ce qu'on avait dit ?) des notes en chinois aussi (qui sont des traductions du français). 

Pour la version anglaise, à la réflexion, est-ce qu'il faut mettre aussi toutes les infos en français, ou seulement quelques infos choisies ? En voyant des situations comme celle-ci, je me dis qu'une version allégée serait une bonne idée. Ne garder que : 
- traduction du mot en français
- traduction des exemples en français

(Je ferme le ticket.)
