### ISSUE TITLE
mini-élément cosmétique : traduction en langue naturelle de \mr

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#97]
Actuellement, il est indiqué "morphologie" : en chinois,【形态】 (comme je l'avais indiqué).
![image](https://github.com/user-attachments/assets/b3b08023-bd0b-49c7-9023-a124ef5f378b)

À la réflexion, il serait nettement plus précis et parlant de dire "Composition morphémique". 

En chinois : cela donnerait 组成语素, "morphèmes constitutifs". 
En français : "Composition morphémique : " 

(Ou "Morphèmes constitutifs :", mais un avantage de "Composition morphémique :" est qu'il n'y a pas à gérer une étiquette différente pour les cas où il y a 2 morphèmes ou plus (=il faudrait accorder au pluriel : "Morphèmes constitutifs") ou un seul qui soit identifié. Dans ce dernier cas, c'est un peu bancal, du fait que l'analyse morphémique ne s'étend pas à l'ensemble du mot : on a juste 1 indice, sur un des morphèmes qui le constitue. Comme si, pour "xylographie", on avait "`Composition morphémique : "-graphie"`", sans indication concernant le premier morphème. Mais bon c'est comme ça que ça se présente : à ce stade du travail, l'analyse morphémique est incomplète pour certains mots, et la typographie est donc à penser en fonction de l'existant.)

En anglais : "Morphemic make-up:"

**Comment by BenjaminGalliot** [comment]
C’est fait.

**Comment by alexis-michaud** [comment]
:+1:
