### ISSUE TITLE
mini-modif liste voyelles & consonnes (en bas de page)

### ISSUE THREAD

**Issue by alexis-michaud** [alexis-michaud/na#99]
Le symbole ɻ note une consonne initiale. Il serait donc à retirer de la liste des voyelles / rimes affichée en bas de page
![image](https://github.com/user-attachments/assets/319ba534-9729-4c09-b392-296a74bc7f33)
et à déplacer vers la liste des consonnes (en page de gauche)
b ɕ d dz dʑ ɖ ɖʐ f g ɣ h j ʝ k kʰ l ɭ ɬ m n ɳ ɲ ŋ p pʰ q qʰ ʁ s ʂ t tʰ ts tsʰ tɕ tɕʰ ʈ ʈʰ ʈʂ ʈʂʰ w w̃ z ʑ ʐ
Il trouverait sa place avant le symbole ʁ : 
... qʰ ɻ ʁ ...

Tandis que ɻ̩ et ɻ̩̃ sont bien à leur place dans la liste des rimes (c'est le même symbole, mais avec un diacritique souscrit qui indique justement que le son sert de sommet de syllabe).

**Comment by alexis-michaud** [comment]
(C'est le genre de modifs que je devrais être en mesure de réaliser moi-même sur les fichiers de configuration)

**Comment by BenjaminGalliot** [comment]
C’est fait. Ces détails ne sont pas accessibles dans le fichier de configuration général car il s’agit là surtout de mise en forme, c’est très différent de la liste des graphèmes pour l’ordre lexicographique, qui est utilisé aussi en amont.

![Copie d'écran_20240925_142550](https://github.com/user-attachments/assets/f9338d3e-27fd-4a9e-be0c-a3f545f5615a)

**Comment by alexis-michaud** [comment]
:+1:
